/*
 * FlashCanvas
 *
 * Copyright (c) 2009      Tim Cameron Ryan
 * Copyright (c) 2009-2011 FlashCanvas Project
 * Released under the MIT/X License
 */

window.ActiveXObject&&!window.CanvasRenderingContext2D&&function(j,l){function A(a){this.code=a;this.message=O[a]}function P(a){this.width=a}function B(a){this.id=a.C++}function r(a){this.G=a;this.id=a.C++}function s(a,b){this.canvas=a;this.B=b;this.d=a.uniqueID;this.D();this.C=0;this.t="";var c=this;setInterval(function(){0===o[c.d]&&c.e()},30)}function x(){if("complete"===l.readyState){l.detachEvent(C,x);for(var a=l.getElementsByTagName(q),b=0,c=a.length;b<c;++b)y.initElement(a[b])}}function D(){var a=
event.srcElement,b=a.parentNode;a.blur();b.focus()}function E(){var a=event.propertyName;if("width"===a||"height"===a){var b=event.srcElement,c=b[a],d=parseInt(c,10);if(isNaN(d)||0>d)d="width"===a?300:150;c===d?(b.style[a]=d+"px",b.getContext("2d").I(b.width,b.height)):b[a]=d}}function F(){j.detachEvent(G,F);for(var a in m){var b=m[a],c=b.firstChild,d;for(d in c)"function"===typeof c[d]&&(c[d]=i);for(d in b)"function"===typeof b[d]&&(b[d]=i);c.detachEvent(H,D);b.detachEvent(I,E)}j[J]=i;j[K]=i;j[L]=
i;j[z]=i;j[M]=i}function t(a){return(""+a).replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;")}function Q(a){return a.toLowerCase()}function h(a){throw new A(a);}function N(a){var b=parseInt(a.width,10),c=parseInt(a.height,10);if(isNaN(b)||0>b)b=300;if(isNaN(c)||0>c)c=150;a.width=b;a.height=c}var i=null,q="canvas",J="CanvasRenderingContext2D",K="CanvasGradient",L="CanvasPattern",z="FlashCanvas",M="G_vmlCanvasManager",H="onfocus",I="onpropertychange",C="onreadystatechange",G="onunload",k;if(!(k=(j[z+
"Options"]||{}).swfPath))k=l.getElementsByTagName("script"),k=k[k.length-1],k=(8<=l.documentMode?k.src:k.getAttribute("src",4)).replace(/[^\/]+$/,"");var u=k+"flashcanvas.swf",e=new function(a){for(var b=0,c=a.length;b<c;b++)this[a[b]]=b}("toDataURL save restore scale rotate translate transform setTransform globalAlpha globalCompositeOperation strokeStyle fillStyle createLinearGradient createRadialGradient createPattern lineWidth lineCap lineJoin miterLimit shadowOffsetX shadowOffsetY shadowBlur shadowColor clearRect fillRect strokeRect beginPath closePath moveTo lineTo quadraticCurveTo bezierCurveTo arcTo rect arc fill stroke clip isPointInPath font textAlign textBaseline fillText strokeText measureText drawImage createImageData getImageData putImageData addColorStop direction resize".split(" ")),
v={},o={},m={},w={};s.prototype={save:function(){this.b();this.c();this.m();this.l();this.z();this.w();this.F.push([this.f,this.g,this.A,this.u,this.j,this.h,this.i,this.k,this.p,this.q,this.n,this.o,this.v,this.r,this.s]);this.a.push(e.save)},restore:function(){var a=this.F;a.length&&(a=a.pop(),this.globalAlpha=a[0],this.globalCompositeOperation=a[1],this.strokeStyle=a[2],this.fillStyle=a[3],this.lineWidth=a[4],this.lineCap=a[5],this.lineJoin=a[6],this.miterLimit=a[7],this.shadowOffsetX=a[8],this.shadowOffsetY=
a[9],this.shadowBlur=a[10],this.shadowColor=a[11],this.font=a[12],this.textAlign=a[13],this.textBaseline=a[14]);this.a.push(e.restore)},scale:function(a,b){this.a.push(e.scale,a,b)},rotate:function(a){this.a.push(e.rotate,a)},translate:function(a,b){this.a.push(e.translate,a,b)},transform:function(a,b,c,d,f,g){this.a.push(e.transform,a,b,c,d,f,g)},setTransform:function(a,b,c,d,f,g){this.a.push(e.setTransform,a,b,c,d,f,g)},b:function(){var a=this.a;this.f!==this.globalAlpha&&(this.f=this.globalAlpha,
a.push(e.globalAlpha,this.f));this.g!==this.globalCompositeOperation&&(this.g=this.globalCompositeOperation,a.push(e.globalCompositeOperation,this.g))},m:function(){if(this.A!==this.strokeStyle){var a=this.A=this.strokeStyle;this.a.push(e.strokeStyle,"object"===typeof a?a.id:a)}},l:function(){if(this.u!==this.fillStyle){var a=this.u=this.fillStyle;this.a.push(e.fillStyle,"object"===typeof a?a.id:a)}},createLinearGradient:function(a,b,c,d){isFinite(a)&&isFinite(b)&&isFinite(c)&&isFinite(d)||h(9);this.a.push(e.createLinearGradient,
a,b,c,d);return new r(this)},createRadialGradient:function(a,b,c,d,f,g){isFinite(a)&&isFinite(b)&&isFinite(c)&&isFinite(d)&&isFinite(f)&&isFinite(g)||h(9);(0>c||0>g)&&h(1);this.a.push(e.createRadialGradient,a,b,c,d,f,g);return new r(this)},createPattern:function(a,b){a||h(17);var c=a.tagName,d,f=this.d;if(c)if(c=c.toLowerCase(),"img"===c)d=a.getAttribute("src",2);else{if(c===q||"video"===c)return;h(17)}else a.src?d=a.src:h(17);"repeat"===b||"no-repeat"===b||"repeat-x"===b||"repeat-y"===b||""===b||
b===i||h(12);this.a.push(e.createPattern,t(d),b);v[f]&&(this.e(),++o[f]);return new B(this)},z:function(){var a=this.a;this.j!==this.lineWidth&&(this.j=this.lineWidth,a.push(e.lineWidth,this.j));this.h!==this.lineCap&&(this.h=this.lineCap,a.push(e.lineCap,this.h));this.i!==this.lineJoin&&(this.i=this.lineJoin,a.push(e.lineJoin,this.i));this.k!==this.miterLimit&&(this.k=this.miterLimit,a.push(e.miterLimit,this.k))},c:function(){var a=this.a;this.p!==this.shadowOffsetX&&(this.p=this.shadowOffsetX,a.push(e.shadowOffsetX,
this.p));this.q!==this.shadowOffsetY&&(this.q=this.shadowOffsetY,a.push(e.shadowOffsetY,this.q));this.n!==this.shadowBlur&&(this.n=this.shadowBlur,a.push(e.shadowBlur,this.n));this.o!==this.shadowColor&&(this.o=this.shadowColor,a.push(e.shadowColor,this.o))},clearRect:function(a,b,c,d){this.a.push(e.clearRect,a,b,c,d)},fillRect:function(a,b,c,d){this.b();this.c();this.l();this.a.push(e.fillRect,a,b,c,d)},strokeRect:function(a,b,c,d){this.b();this.c();this.m();this.z();this.a.push(e.strokeRect,a,b,
c,d)},beginPath:function(){this.a.push(e.beginPath)},closePath:function(){this.a.push(e.closePath)},moveTo:function(a,b){this.a.push(e.moveTo,a,b)},lineTo:function(a,b){this.a.push(e.lineTo,a,b)},quadraticCurveTo:function(a,b,c,d){this.a.push(e.quadraticCurveTo,a,b,c,d)},bezierCurveTo:function(a,b,c,d,f,g){this.a.push(e.bezierCurveTo,a,b,c,d,f,g)},arcTo:function(a,b,c,d,f){0>f&&isFinite(f)&&h(1);this.a.push(e.arcTo,a,b,c,d,f)},rect:function(a,b,c,d){this.a.push(e.rect,a,b,c,d)},arc:function(a,b,c,
d,f,g){0>c&&isFinite(c)&&h(1);this.a.push(e.arc,a,b,c,d,f,g?1:0)},fill:function(){this.b();this.c();this.l();this.a.push(e.fill)},stroke:function(){this.b();this.c();this.m();this.z();this.a.push(e.stroke)},clip:function(){this.a.push(e.clip)},w:function(){var a=this.a;if(this.v!==this.font)try{var b=w[this.d];b.style.font=this.v=this.font;var c=b.currentStyle;a.push(e.font,[c.fontStyle,c.fontWeight,b.offsetHeight,c.fontFamily].join(" "))}catch(d){}this.r!==this.textAlign&&(this.r=this.textAlign,
a.push(e.textAlign,this.r));this.s!==this.textBaseline&&(this.s=this.textBaseline,a.push(e.textBaseline,this.s));this.t!==this.canvas.currentStyle.direction&&(this.t=this.canvas.currentStyle.direction,a.push(e.direction,this.t))},fillText:function(a,b,c,d){this.b();this.l();this.c();this.w();this.a.push(e.fillText,t(a),b,c,void 0===d?Infinity:d)},strokeText:function(a,b,c,d){this.b();this.m();this.c();this.w();this.a.push(e.strokeText,t(a),b,c,void 0===d?Infinity:d)},measureText:function(a){var b=
w[this.d];try{b.style.font=this.font}catch(c){}b.innerText=a.replace(/[ \n\f\r]/g,"\t");return new P(b.offsetWidth)},drawImage:function(a,b,c,d,f,g,j,k,l){a||h(17);var i=a.tagName,n,p=arguments.length,m=this.d;if(i)if(i=i.toLowerCase(),"img"===i)n=a.getAttribute("src",2);else{if(i===q||"video"===i)return;h(17)}else a.src?n=a.src:h(17);this.b();this.c();n=t(n);if(3===p)this.a.push(e.drawImage,p,n,b,c);else if(5===p)this.a.push(e.drawImage,p,n,b,c,d,f);else if(9===p)(0===d||0===f)&&h(1),this.a.push(e.drawImage,
p,n,b,c,d,f,g,j,k,l);else return;v[m]&&(this.e(),++o[m])},D:function(){this.globalAlpha=this.f=1;this.globalCompositeOperation=this.g="source-over";this.fillStyle=this.u=this.strokeStyle=this.A="#000000";this.lineWidth=this.j=1;this.lineCap=this.h="butt";this.lineJoin=this.i="miter";this.miterLimit=this.k=10;this.shadowBlur=this.n=this.shadowOffsetY=this.q=this.shadowOffsetX=this.p=0;this.shadowColor=this.o="rgba(0, 0, 0, 0.0)";this.font=this.v="10px sans-serif";this.textAlign=this.r="start";this.textBaseline=
this.s="alphabetic";this.a=[];this.F=[]},H:function(){var a=this.a;this.a=[];return a},e:function(){var a=this.H();if(0<a.length)return eval(this.B.CallFunction('\x3cinvoke name\x3d"executeCommand" returntype\x3d"javascript"\x3e\x3carguments\x3e\x3cstring\x3e'+a.join("\x26#0;")+"\x3c/string\x3e\x3c/arguments\x3e\x3c/invoke\x3e"))},I:function(a,b){this.e();this.D();0<a&&(this.B.width=a);0<b&&(this.B.height=b);this.a.push(e.resize,a,b)}};r.prototype={addColorStop:function(a,b){(isNaN(a)||0>a||1<a)&&
h(1);this.G.a.push(e.addColorStop,this.id,a,b)}};A.prototype=Error();var O={1:"INDEX_SIZE_ERR",9:"NOT_SUPPORTED_ERR",11:"INVALID_STATE_ERR",12:"SYNTAX_ERR",17:"TYPE_MISMATCH_ERR",18:"SECURITY_ERR"},y={initElement:function(a){if(a.getContext)return a;var b=a.uniqueID,c="external"+b;v[b]=!1;o[b]=1;N(a);a.innerHTML='\x3cobject classid\x3d"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase\x3d"'+location.protocol+'//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version\x3d9,0,0,0" width\x3d"100%" height\x3d"100%" id\x3d"'+
c+'"\x3e\x3cparam name\x3d"allowScriptAccess" value\x3d"always"\x3e\x3cparam name\x3d"flashvars" value\x3d"id\x3d'+c+'"\x3e\x3cparam name\x3d"wmode" value\x3d"transparent"\x3e\x3c/object\x3e\x3cspan style\x3d"margin:0;padding:0;border:0;display:inline-block;position:static;height:1em;overflow:visible;white-space:nowrap"\x3e\x3c/span\x3e';m[b]=a;var d=a.firstChild;w[b]=a.lastChild;var f=l.body.contains;if(f(a))d.movie=u;else var g=setInterval(function(){f(a)&&(clearInterval(g),d.movie=u)},0);if("BackCompat"===
l.compatMode||!j.XMLHttpRequest)w[b].style.overflow="hidden";var h=new s(a,d);a.getContext=function(a){return"2d"===a?h:i};a.toDataURL=function(a,b){"image/jpeg"===(""+a).replace(/[A-Z]+/g,Q)?h.a.push(e.toDataURL,a,"number"===typeof b?b:""):h.a.push(e.toDataURL,a);return h.e()};d.attachEvent(H,D);return a},saveImage:function(a){a.firstChild.saveImage()},setOptions:function(){},trigger:function(a,b){m[a].fireEvent("on"+b)},unlock:function(a,b){o[a]&&--o[a];if(b){var c=m[a],d=c.firstChild,e,g;N(c);
e=c.width;g=c.height;c.style.width=e+"px";c.style.height=g+"px";0<e&&(d.width=e);0<g&&(d.height=g);d.resize(e,g);c.attachEvent(I,E);v[a]=!0}}};l.createElement(q);l.createStyleSheet().cssText=q+"{display:inline-block;overflow:hidden;width:300px;height:150px}";"complete"===l.readyState?x():l.attachEvent(C,x);j.attachEvent(G,F);0===u.indexOf(location.protocol+"//"+location.host+"/")&&(k=new ActiveXObject("Microsoft.XMLHTTP"),k.open("GET",u,!1),k.send(i));j[J]=s;j[K]=r;j[L]=B;j[z]=y;j[M]={init:function(){},
init_:function(){},initElement:y.initElement};keep=s.measureText}(window,document);