/*!
 * jQuery JavaScript Library v1.7.1
 * http://jquery.com/
 *
 * Copyright 2011, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2011, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
 * Date: Mon Nov 21 21:11:03 2011 -0500
 */

/*!
 * Sizzle CSS Selector Engine
 *  Copyright 2011, The Dojo Foundation
 *  Released under the MIT, BSD, and GPL Licenses.
 *  More information: http://sizzlejs.com/
 */

(function(q){function Pa(a,b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace(Ub,"-$1").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:d.isNumeric(c)?parseFloat(c):Vb.test(c)?d.parseJSON(c):c}catch(e){}d.data(a,b,c)}else c=void 0;return c}function ta(a){for(var b in a)if(!("data"===b&&d.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;return!0}function Qa(a,b,c){var e=b+"defer",f=b+"queue",g=b+"mark",h=d._data(a,e);h&&(("queue"===c||!d._data(a,
f))&&("mark"===c||!d._data(a,g)))&&setTimeout(function(){!d._data(a,f)&&!d._data(a,g)&&(d.removeData(a,e,!0),h.fire())},0)}function L(){return!1}function $(){return!0}function Ra(a,b,c){b=b||0;if(d.isFunction(b))return d.grep(a,function(a,e){return!!b.call(a,e,a)===c});if(b.nodeType)return d.grep(a,function(a){return a===b===c});if("string"===typeof b){var e=d.grep(a,function(a){return 1===a.nodeType});if(Wb.test(b))return d.filter(b,e,!c);b=d.filter(b,e)}return d.grep(a,function(a){return 0<=d.inArray(a,
b)===c})}function Sa(a){var b=Ta.split("|");a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Ua(a,b){if(1===b.nodeType&&d.hasData(a)){var c,e,f;e=d._data(a);var g=d._data(b,e),h=e.events;if(h)for(c in delete g.handle,g.events={},h){e=0;for(f=h[c].length;e<f;e++)d.event.add(b,c+(h[c][e].namespace?".":"")+h[c][e].namespace,h[c][e],h[c][e].data)}g.data&&(g.data=d.extend({},g.data))}}function Va(a,b){var c;if(1===b.nodeType){b.clearAttributes&&
b.clearAttributes();b.mergeAttributes&&b.mergeAttributes(a);c=b.nodeName.toLowerCase();if("object"===c)b.outerHTML=a.outerHTML;else if("input"===c&&("checkbox"===a.type||"radio"===a.type))a.checked&&(b.defaultChecked=b.checked=a.checked),b.value!==a.value&&(b.value=a.value);else if("option"===c)b.selected=a.defaultSelected;else if("input"===c||"textarea"===c)b.defaultValue=a.defaultValue;b.removeAttribute(d.expando)}}function aa(a){return"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName("*"):
"undefined"!==typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function Wa(a){if("checkbox"===a.type||"radio"===a.type)a.defaultChecked=a.checked}function Xa(a){var b=(a.nodeName||"").toLowerCase();"input"===b?Wa(a):"script"!==b&&"undefined"!==typeof a.getElementsByTagName&&d.grep(a.getElementsByTagName("input"),Wa)}function Xb(a,b){b.src?d.ajax({url:b.src,async:!1,dataType:"script"}):d.globalEval((b.text||b.textContent||b.innerHTML||"").replace(Yb,"/*$0*/"));b.parentNode&&b.parentNode.removeChild(b)}
function Ya(a,b,c){var e="width"===b?a.offsetWidth:a.offsetHeight,f="width"===b?Zb:$b,g=0,h=f.length;if(0<e){if("border"!==c)for(;g<h;g++)c||(e-=parseFloat(d.css(a,"padding"+f[g]))||0),e="margin"===c?e+(parseFloat(d.css(a,c+f[g]))||0):e-(parseFloat(d.css(a,"border"+f[g]+"Width"))||0);return e+"px"}e=G(a,b,b);if(0>e||null==e)e=a.style[b]||0;e=parseFloat(e)||0;if(c)for(;g<h;g++)e+=parseFloat(d.css(a,"padding"+f[g]))||0,"padding"!==c&&(e+=parseFloat(d.css(a,"border"+f[g]+"Width"))||0),"margin"===c&&
(e+=parseFloat(d.css(a,c+f[g]))||0);return e+"px"}function Za(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");if(d.isFunction(c))for(var e=b.toLowerCase().split($a),f=0,g=e.length,h,i;f<g;f++)h=e[f],(i=/^\+/.test(h))&&(h=h.substr(1)||"*"),h=a[h]=a[h]||[],h[i?"unshift":"push"](c)}}function ba(a,b,c,e,d,g){d=d||b.dataTypes[0];g=g||{};g[d]=!0;d=a[d];for(var h=0,i=d?d.length:0,j=a===ua,n;h<i&&(j||!n);h++)n=d[h](b,c,e),"string"===typeof n&&(!j||g[n]?n=void 0:(b.dataTypes.unshift(n),n=ba(a,b,c,
e,n,g)));if((j||!n)&&!g["*"])n=ba(a,b,c,e,"*",g);return n}function ab(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e)}function va(a,b,c,e){if(d.isArray(b))d.each(b,function(b,f){c||ac.test(a)?e(a,f):va(a+"["+("object"===typeof f||d.isArray(f)?b:"")+"]",f,c,e)});else if(!c&&null!=b&&"object"===typeof b)for(var f in b)va(a+"["+f+"]",b[f],c,e);else e(a,b)}function bb(){try{return new q.XMLHttpRequest}catch(a){}}function cb(){setTimeout(bc,
0);return ca=d.now()}function bc(){ca=void 0}function B(a,b){var c={};d.each(db.concat.apply([],db.slice(0,b)),function(){c[this]=a});return c}function eb(a){if(!wa[a]){var b=l.body,c=d("\x3c"+a+"\x3e").appendTo(b),e=c.css("display");c.remove();if("none"===e||""===e){v||(v=l.createElement("iframe"),v.frameBorder=v.width=v.height=0);b.appendChild(v);if(!K||!v.createElement)K=(v.contentWindow||v.contentDocument).document,K.write(("CSS1Compat"===l.compatMode?"\x3c!doctype html\x3e":"")+"\x3chtml\x3e\x3cbody\x3e"),
K.close();c=K.createElement(a);K.body.appendChild(c);e=d.css(c,"display");b.removeChild(v)}wa[a]=e}return wa[a]}function xa(a){return d.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var l=q.document,cc=q.location,d,fb=function(){if(!k.isReady){try{l.documentElement.doScroll("left")}catch(a){setTimeout(fb,1);return}k.ready()}},k=function(a,b){return new k.fn.init(a,b,gb)},dc=q.jQuery,ec=q.$,gb,fc=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,hb=/\S/,ib=/^\s+/,jb=/\s+$/,gc=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,
hc=/^[\],:{}\s]*$/,ic=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,jc=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,kc=/(?:^|:|,)(?:\s*\[)+/g,lc=/(webkit)[ \/]([\w.]+)/,mc=/(opera)(?:.*version)?[ \/]([\w.]+)/,nc=/(msie) ([\w.]+)/,oc=/(mozilla)(?:.*? rv:([\w.]+))?/,pc=/-([a-z]|[0-9])/ig,qc=/^-ms-/,rc=function(a,b){return(b+"").toUpperCase()},sc=q.navigator.userAgent,da,ea,C,tc=Object.prototype.toString,ya=Object.prototype.hasOwnProperty,za=Array.prototype.push,W=Array.prototype.slice,
kb=String.prototype.trim,lb=Array.prototype.indexOf,mb={};k.fn=k.prototype={constructor:k,init:function(a,b,c){var e;if(!a)return this;if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if("body"===a&&!b&&l.body)return this.context=l,this[0]=l.body,this.selector=a,this.length=1,this;if("string"===typeof a){if((e="\x3c"===a.charAt(0)&&"\x3e"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:fc.exec(a))&&(e[1]||!b)){if(e[1])return c=(b=b instanceof k?b[0]:b)?b.ownerDocument||b:l,(a=gc.exec(a))?
k.isPlainObject(b)?(a=[l.createElement(a[1])],k.fn.attr.call(a,b,!0)):a=[c.createElement(a[1])]:(a=k.buildFragment([e[1]],[c]),a=(a.cacheable?k.clone(a.fragment):a.fragment).childNodes),k.merge(this,a);if((b=l.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return c.find(a);this.length=1;this[0]=b}this.context=l;this.selector=a;return this}return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a)}if(k.isFunction(a))return c.ready(a);void 0!==a.selector&&(this.selector=a.selector,this.context=
a.context);return k.makeArray(a,this)},selector:"",jquery:"1.7.1",length:0,size:function(){return this.length},toArray:function(){return W.call(this,0)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a,b,c){var e=this.constructor();k.isArray(a)?za.apply(e,a):k.merge(e,a);e.prevObject=this;e.context=this.context;"find"===b?e.selector=this.selector+(this.selector?" ":"")+c:b&&(e.selector=this.selector+"."+b+"("+c+")");return e},each:function(a,b){return k.each(this,
a,b)},ready:function(a){k.bindReady();ea.add(a);return this},eq:function(a){a=+a;return-1===a?this.slice(a):this.slice(a,a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(W.apply(this,arguments),"slice",W.call(arguments).join(","))},map:function(a){return this.pushStack(k.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:za,sort:[].sort,splice:[].splice};k.fn.init.prototype=
k.fn;k.extend=k.fn.extend=function(){var a,b,c,e,d,g=arguments[0]||{},h=1,i=arguments.length,j=!1;"boolean"===typeof g&&(j=g,g=arguments[1]||{},h=2);"object"!==typeof g&&!k.isFunction(g)&&(g={});i===h&&(g=this,--h);for(;h<i;h++)if(null!=(a=arguments[h]))for(b in a)c=g[b],e=a[b],g!==e&&(j&&e&&(k.isPlainObject(e)||(d=k.isArray(e)))?(d?(d=!1,c=c&&k.isArray(c)?c:[]):c=c&&k.isPlainObject(c)?c:{},g[b]=k.extend(j,c,e)):void 0!==e&&(g[b]=e));return g};k.extend({noConflict:function(a){q.$===k&&(q.$=ec);a&&
q.jQuery===k&&(q.jQuery=dc);return k},isReady:!1,readyWait:1,holdReady:function(a){a?k.readyWait++:k.ready(!0)},ready:function(a){if(!0===a&&!--k.readyWait||!0!==a&&!k.isReady){if(!l.body)return setTimeout(k.ready,1);k.isReady=!0;!0!==a&&0<--k.readyWait||(ea.fireWith(l,[k]),k.fn.trigger&&k(l).trigger("ready").off("ready"))}},bindReady:function(){if(!ea){ea=k.Callbacks("once memory");if("complete"===l.readyState)return setTimeout(k.ready,1);if(l.addEventListener)l.addEventListener("DOMContentLoaded",
C,!1),q.addEventListener("load",k.ready,!1);else if(l.attachEvent){l.attachEvent("onreadystatechange",C);q.attachEvent("onload",k.ready);var a=!1;try{a=null==q.frameElement}catch(b){}l.documentElement.doScroll&&a&&fb()}}},isFunction:function(a){return"function"===k.type(a)},isArray:Array.isArray||function(a){return"array"===k.type(a)},isWindow:function(a){return a&&"object"===typeof a&&"setInterval"in a},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==
a?String(a):mb[tc.call(a)]||"object"},isPlainObject:function(a){if(!a||"object"!==k.type(a)||a.nodeType||k.isWindow(a))return!1;try{if(a.constructor&&!ya.call(a,"constructor")&&!ya.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===c||ya.call(a,c)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseJSON:function(a){if("string"!==typeof a||!a)return null;a=k.trim(a);if(q.JSON&&q.JSON.parse)return q.JSON.parse(a);
if(hc.test(a.replace(ic,"@").replace(jc,"]").replace(kc,"")))return(new Function("return "+a))();k.error("Invalid JSON: "+a)},parseXML:function(a){var b,c;try{q.DOMParser?(c=new DOMParser,b=c.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=void 0}(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)&&k.error("Invalid XML: "+a);return b},noop:function(){},globalEval:function(a){a&&hb.test(a)&&(q.execScript||function(a){q.eval.call(q,
a)})(a)},camelCase:function(a){return a.replace(qc,"ms-").replace(pc,rc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,c){var e,d=0,g=a.length,h=void 0===g||k.isFunction(a);if(c)if(h)for(e in a){if(!1===b.apply(a[e],c))break}else for(;d<g&&!1!==b.apply(a[d++],c););else if(h)for(e in a){if(!1===b.call(a[e],e,a[e]))break}else for(;d<g&&!1!==b.call(a[d],d,a[d++]););return a},trim:kb?function(a){return null==a?"":kb.call(a)}:function(a){return null==
a?"":a.toString().replace(ib,"").replace(jb,"")},makeArray:function(a,b){var c=b||[];if(null!=a){var e=k.type(a);null==a.length||"string"===e||"function"===e||"regexp"===e||k.isWindow(a)?za.call(c,a):k.merge(c,a)}return c},inArray:function(a,b,c){var e;if(b){if(lb)return lb.call(b,a,c);e=b.length;for(c=c?0>c?Math.max(0,e+c):c:0;c<e;c++)if(c in b&&b[c]===a)return c}return-1},merge:function(a,b){var c=a.length,e=0;if("number"===typeof b.length)for(var d=b.length;e<d;e++)a[c++]=b[e];else for(;void 0!==
b[e];)a[c++]=b[e++];a.length=c;return a},grep:function(a,b,c){var e=[],d;c=!!c;for(var g=0,h=a.length;g<h;g++)d=!!b(a[g],g),c!==d&&e.push(a[g]);return e},map:function(a,b,c){var e,d,g=[],h=0,i=a.length;if(a instanceof k||void 0!==i&&"number"===typeof i&&(0<i&&a[0]&&a[i-1]||0===i||k.isArray(a)))for(;h<i;h++)e=b(a[h],h,c),null!=e&&(g[g.length]=e);else for(d in a)e=b(a[d],d,c),null!=e&&(g[g.length]=e);return g.concat.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var c=a[b];b=a;a=c}if(k.isFunction(a)){var e=
W.call(arguments,2),c=function(){return a.apply(b,e.concat(W.call(arguments)))};c.guid=a.guid=a.guid||c.guid||k.guid++;return c}},access:function(a,b,c,e,d,g){var h=a.length;if("object"===typeof b){for(var i in b)k.access(a,i,b[i],e,d,c);return a}if(void 0!==c){e=!g&&e&&k.isFunction(c);for(i=0;i<h;i++)d(a[i],b,e?c.call(a[i],i,d(a[i],b)):c,g);return a}return h?d(a[0],b):void 0},now:function(){return(new Date).getTime()},uaMatch:function(a){a=a.toLowerCase();a=lc.exec(a)||mc.exec(a)||nc.exec(a)||0>
a.indexOf("compatible")&&oc.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},sub:function(){function a(b,e){return new a.fn.init(b,e)}k.extend(!0,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=function(c,e){e&&(e instanceof k&&!(e instanceof a))&&(e=a(e));return k.fn.init.call(this,c,e,b)};a.fn.init.prototype=a.fn;var b=a(l);return a},browser:{}});k.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){mb["[object "+
b+"]"]=b.toLowerCase()});da=k.uaMatch(sc);da.browser&&(k.browser[da.browser]=!0,k.browser.version=da.version);k.browser.webkit&&(k.browser.safari=!0);hb.test("\u00a0")&&(ib=/^[\s\xA0]+/,jb=/[\s\xA0]+$/);gb=k(l);l.addEventListener?C=function(){l.removeEventListener("DOMContentLoaded",C,!1);k.ready()}:l.attachEvent&&(C=function(){"complete"===l.readyState&&(l.detachEvent("onreadystatechange",C),k.ready())});d=k;var nb={};d.Callbacks=function(a){var b;if(a){if(!(b=nb[a])){b=a;var c=nb[b]={},e,f;b=b.split(/\s+/);
e=0;for(f=b.length;e<f;e++)c[b[e]]=!0;b=c}}else b={};a=b;var g=[],h=[],i,j,n,H,l,k=function(b){var c,e,f,h;c=0;for(e=b.length;c<e;c++)f=b[c],h=d.type(f),"array"===h?k(f):"function"===h&&(!a.unique||!o.has(f))&&g.push(f)},m=function(b,c){c=c||[];i=!a.memory||[b,c];j=!0;l=n||0;n=0;for(H=g.length;g&&l<H;l++)if(!1===g[l].apply(b,c)&&a.stopOnFalse){i=!0;break}j=!1;g&&(a.once?!0===i?o.disable():g=[]:h&&h.length&&(i=h.shift(),o.fireWith(i[0],i[1])))},o={add:function(){if(g){var a=g.length;k(arguments);j?
H=g.length:i&&!0!==i&&(n=a,m(i[0],i[1]))}return this},remove:function(){if(g)for(var b=arguments,c=0,e=b.length;c<e;c++)for(var d=0;d<g.length&&!(b[c]===g[d]&&(j&&d<=H&&(H--,d<=l&&l--),g.splice(d--,1),a.unique));d++);return this},has:function(a){if(g)for(var b=0,c=g.length;b<c;b++)if(a===g[b])return!0;return!1},empty:function(){g=[];return this},disable:function(){g=h=i=void 0;return this},disabled:function(){return!g},lock:function(){h=void 0;(!i||!0===i)&&o.disable();return this},locked:function(){return!h},
fireWith:function(b,c){h&&(j?a.once||h.push([b,c]):(!a.once||!i)&&m(b,c));return this},fire:function(){o.fireWith(this,arguments);return this},fired:function(){return!!i}};return o};var Ba=[].slice;d.extend({Deferred:function(a){var b=d.Callbacks("once memory"),c=d.Callbacks("once memory"),e=d.Callbacks("memory"),f="pending",g={resolve:b,reject:c,notify:e},h={done:b.add,fail:c.add,progress:e.add,state:function(){return f},isResolved:b.fired,isRejected:c.fired,then:function(a,b,c){i.done(a).fail(b).progress(c);
return this},always:function(){i.done.apply(i,arguments).fail.apply(i,arguments);return this},pipe:function(a,b,c){return d.Deferred(function(e){d.each({done:[a,"resolve"],fail:[b,"reject"],progress:[c,"notify"]},function(a,b){var c=b[0],f=b[1],g;if(d.isFunction(c))i[a](function(){if((g=c.apply(this,arguments))&&d.isFunction(g.promise))g.promise().then(e.resolve,e.reject,e.notify);else e[f+"With"](this===i?e:this,[g])});else i[a](e[f])})}).promise()},promise:function(a){if(null==a)a=h;else for(var b in h)a[b]=
h[b];return a}},i=h.promise({}),j;for(j in g)i[j]=g[j].fire,i[j+"With"]=g[j].fireWith;i.done(function(){f="resolved"},c.disable,e.lock).fail(function(){f="rejected"},b.disable,e.lock);a&&a.call(i,i);return i},when:function(a){function b(a){return function(b){e[a]=1<arguments.length?Ba.call(arguments,0):b;--i||j.resolveWith(j,e)}}function c(a){return function(b){h[a]=1<arguments.length?Ba.call(arguments,0):b;j.notifyWith(n,h)}}var e=Ba.call(arguments,0),f=0,g=e.length,h=Array(g),i=g,j=1>=g&&a&&d.isFunction(a.promise)?
a:d.Deferred(),n=j.promise();if(1<g){for(;f<g;f++)e[f]&&e[f].promise&&d.isFunction(e[f].promise)?e[f].promise().then(b(f),j.reject,c(f)):--i;i||j.resolveWith(j,e)}else j!==a&&j.resolveWith(j,g?[a]:[]);return n}});var uc=d,Ca;var r,Da,M,fa,ga,u,Q,I,X,ha,Ea,R,o=l.createElement("div");o.setAttribute("className","t");o.innerHTML="   \x3clink/\x3e\x3ctable\x3e\x3c/table\x3e\x3ca href\x3d'/a' style\x3d'top:1px;float:left;opacity:.55;'\x3ea\x3c/a\x3e\x3cinput type\x3d'checkbox'/\x3e";Da=o.getElementsByTagName("*");
M=o.getElementsByTagName("a")[0];if(!Da||!Da.length||!M)Ca={};else{fa=l.createElement("select");ga=fa.appendChild(l.createElement("option"));u=o.getElementsByTagName("input")[0];r={leadingWhitespace:3===o.firstChild.nodeType,tbody:!o.getElementsByTagName("tbody").length,htmlSerialize:!!o.getElementsByTagName("link").length,style:/top/.test(M.getAttribute("style")),hrefNormalized:"/a"===M.getAttribute("href"),opacity:/^0.55/.test(M.style.opacity),cssFloat:!!M.style.cssFloat,checkOn:"on"===u.value,
optSelected:ga.selected,getSetAttribute:"t"!==o.className,enctype:!!l.createElement("form").enctype,html5Clone:"\x3c:nav\x3e\x3c/:nav\x3e"!==l.createElement("nav").cloneNode(!0).outerHTML,submitBubbles:!0,changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0};u.checked=!0;r.noCloneChecked=u.cloneNode(!0).checked;fa.disabled=!0;r.optDisabled=!ga.disabled;try{delete o.test}catch(ld){r.deleteExpando=!1}!o.addEventListener&&
(o.attachEvent&&o.fireEvent)&&(o.attachEvent("onclick",function(){r.noCloneEvent=!1}),o.cloneNode(!0).fireEvent("onclick"));u=l.createElement("input");u.value="t";u.setAttribute("type","radio");r.radioValue="t"===u.value;u.setAttribute("checked","checked");o.appendChild(u);I=l.createDocumentFragment();I.appendChild(o.lastChild);r.checkClone=I.cloneNode(!0).cloneNode(!0).lastChild.checked;r.appendChecked=u.checked;I.removeChild(u);I.appendChild(o);o.innerHTML="";q.getComputedStyle&&(Q=l.createElement("div"),
Q.style.width="0",Q.style.marginRight="0",o.style.width="2px",o.appendChild(Q),r.reliableMarginRight=0===(parseInt((q.getComputedStyle(Q,null)||{marginRight:0}).marginRight,10)||0));if(o.attachEvent)for(Ea in{submit:1,change:1,focusin:1})ha="on"+Ea,R=ha in o,R||(o.setAttribute(ha,"return;"),R="function"===typeof o[ha]),r[Ea+"Bubbles"]=R;I.removeChild(o);I=fa=ga=Q=o=u=null;d(function(){var a,b,c,e,f=l.getElementsByTagName("body")[0];f&&(a=l.createElement("div"),a.style.cssText="visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px",
f.insertBefore(a,f.firstChild),o=l.createElement("div"),a.appendChild(o),o.innerHTML="\x3ctable\x3e\x3ctr\x3e\x3ctd style\x3d'padding:0;border:0;display:none'\x3e\x3c/td\x3e\x3ctd\x3et\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e",X=o.getElementsByTagName("td"),R=0===X[0].offsetHeight,X[0].style.display="",X[1].style.display="none",r.reliableHiddenOffsets=R&&0===X[0].offsetHeight,o.innerHTML="",o.style.width=o.style.paddingLeft="1px",d.boxModel=r.boxModel=2===o.offsetWidth,"undefined"!==typeof o.style.zoom&&
(o.style.display="inline",o.style.zoom=1,r.inlineBlockNeedsLayout=2===o.offsetWidth,o.style.display="",o.innerHTML="\x3cdiv style\x3d'width:4px;'\x3e\x3c/div\x3e",r.shrinkWrapBlocks=2!==o.offsetWidth),o.style.cssText="position:absolute;top:0;left:0;width:1px;height:1px;margin:0;visibility:hidden;border:0;",o.innerHTML="\x3cdiv style\x3d'position:absolute;top:0;left:0;width:1px;height:1px;margin:0;border:5px solid #000;padding:0;'\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3ctable style\x3d'position:absolute;top:0;left:0;width:1px;height:1px;margin:0;border:5px solid #000;padding:0;' cellpadding\x3d'0' cellspacing\x3d'0'\x3e\x3ctr\x3e\x3ctd\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e",
b=o.firstChild,c=b.firstChild,e=b.nextSibling.firstChild.firstChild,e={doesNotAddBorder:5!==c.offsetTop,doesAddBorderForTableAndCells:5===e.offsetTop},c.style.position="fixed",c.style.top="20px",e.fixedPosition=20===c.offsetTop||15===c.offsetTop,c.style.position=c.style.top="",b.style.overflow="hidden",b.style.position="relative",e.subtractsBorderForOverflowNotVisible=-5===c.offsetTop,e.doesNotIncludeMarginInBodyOffset=1!==f.offsetTop,f.removeChild(a),o=null,d.extend(r,e))});Ca=r}uc.support=Ca;var Vb=
/^(?:\{.*\}|\[.*\])$/,Ub=/([A-Z])/g;d.extend({cache:{},uuid:0,expando:"jQuery"+(d.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?d.cache[a[d.expando]]:a[d.expando];return!!a&&!ta(a)},data:function(a,b,c,e){if(d.acceptData(a)){var f;f=d.expando;var g="string"===typeof b,h=a.nodeType,i=h?d.cache:a,j=h?a[f]:a[f]&&f,n="events"===b;if(j&&i[j]&&(n||e||i[j].data)||!(g&&void 0===c)){j||(h?a[f]=j=++d.uuid:
j=f);i[j]||(i[j]={},h||(i[j].toJSON=d.noop));if("object"===typeof b||"function"===typeof b)e?i[j]=d.extend(i[j],b):i[j].data=d.extend(i[j].data,b);f=a=i[j];e||(a.data||(a.data={}),a=a.data);void 0!==c&&(a[d.camelCase(b)]=c);if(n&&!a[b])return f.events;g?(c=a[b],null==c&&(c=a[d.camelCase(b)])):c=a;return c}}},removeData:function(a,b,c){if(d.acceptData(a)){var e,f,g,h=d.expando,i=a.nodeType,j=i?d.cache:a,n=i?a[h]:h;if(j[n]){if(b&&(e=c?j[n]:j[n].data)){d.isArray(b)||(b in e?b=[b]:(b=d.camelCase(b),b=
b in e?[b]:b.split(" ")));f=0;for(g=b.length;f<g;f++)delete e[b[f]];if(!(c?ta:d.isEmptyObject)(e))return}if(!c&&(delete j[n].data,!ta(j[n])))return;d.support.deleteExpando||!j.setInterval?delete j[n]:j[n]=null;i&&(d.support.deleteExpando?delete a[h]:a.removeAttribute?a.removeAttribute(h):a[h]=null)}}},_data:function(a,b,c){return d.data(a,b,c,!0)},acceptData:function(a){if(a.nodeName){var b=d.noData[a.nodeName.toLowerCase()];if(b)return!(!0===b||a.getAttribute("classid")!==b)}return!0}});d.fn.extend({data:function(a,
b){var c,e,f,g=null;if("undefined"===typeof a){if(this.length&&(g=d.data(this[0]),1===this[0].nodeType&&!d._data(this[0],"parsedAttrs"))){e=this[0].attributes;for(var h=0,i=e.length;h<i;h++)f=e[h].name,0===f.indexOf("data-")&&(f=d.camelCase(f.substring(5)),Pa(this[0],f,g[f]));d._data(this[0],"parsedAttrs",!0)}return g}if("object"===typeof a)return this.each(function(){d.data(this,a)});c=a.split(".");c[1]=c[1]?"."+c[1]:"";return void 0===b?(g=this.triggerHandler("getData"+c[1]+"!",[c[0]]),void 0===
g&&this.length&&(g=d.data(this[0],a),g=Pa(this[0],a,g)),void 0===g&&c[1]?this.data(c[0]):g):this.each(function(){var e=d(this),f=[c[0],b];e.triggerHandler("setData"+c[1]+"!",f);d.data(this,a,b);e.triggerHandler("changeData"+c[1]+"!",f)})},removeData:function(a){return this.each(function(){d.removeData(this,a)})}});d.extend({_mark:function(a,b){a&&(b=(b||"fx")+"mark",d._data(a,b,(d._data(a,b)||0)+1))},_unmark:function(a,b,c){!0!==a&&(c=b,b=a,a=!1);if(b){c=c||"fx";var e=c+"mark";(a=a?0:(d._data(b,e)||
1)-1)?d._data(b,e,a):(d.removeData(b,e,!0),Qa(b,c,"mark"))}},queue:function(a,b,c){var e;if(a)return b=(b||"fx")+"queue",e=d._data(a,b),c&&(!e||d.isArray(c)?e=d._data(a,b,d.makeArray(c)):e.push(c)),e||[]},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.shift(),f={};"inprogress"===e&&(e=c.shift());e&&("fx"===b&&c.unshift("inprogress"),d._data(a,b+".run",f),e.call(a,function(){d.dequeue(a,b)},f));c.length||(d.removeData(a,b+"queue "+b+".run",!0),Qa(a,b,"queue"))}});d.fn.extend({queue:function(a,
b){"string"!==typeof a&&(b=a,a="fx");return void 0===b?d.queue(this[0],a):this.each(function(){var c=d.queue(this,a,b);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},delay:function(a,b){a=d.fx?d.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,e){var d=setTimeout(b,a);e.stop=function(){clearTimeout(d)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a){function b(){--g||c.resolveWith(e,[e])}"string"!==
typeof a&&(a=void 0);a=a||"fx";var c=d.Deferred(),e=this,f=e.length,g=1,h=a+"defer",i=a+"queue";a+="mark";for(var j;f--;)if(j=d.data(e[f],h,void 0,!0)||(d.data(e[f],i,void 0,!0)||d.data(e[f],a,void 0,!0))&&d.data(e[f],h,d.Callbacks("once memory"),!0))g++,j.add(b);b();return c.promise()}});var pb=/[\n\t\r]/g,ia=/\s+/,vc=/\r/g,wc=/^(?:button|input)$/i,xc=/^(?:button|input|object|select|textarea)$/i,yc=/^a(?:rea)?$/i,qb=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,
rb=d.support.getSetAttribute,w,sb,tb;d.fn.extend({attr:function(a,b){return d.access(this,a,b,!0,d.attr)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})},prop:function(a,b){return d.access(this,a,b,!0,d.prop)},removeProp:function(a){a=d.propFix[a]||a;return this.each(function(){try{this[a]=void 0,delete this[a]}catch(b){}})},addClass:function(a){var b,c,e,f,g,h,i;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,this.className))});if(a&&"string"===
typeof a){b=a.split(ia);c=0;for(e=this.length;c<e;c++)if(f=this[c],1===f.nodeType)if(!f.className&&1===b.length)f.className=a;else{g=" "+f.className+" ";h=0;for(i=b.length;h<i;h++)~g.indexOf(" "+b[h]+" ")||(g+=b[h]+" ");f.className=d.trim(g)}}return this},removeClass:function(a){var b,c,e,f,g,h,i;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,b,this.className))});if(a&&"string"===typeof a||void 0===a){b=(a||"").split(ia);c=0;for(e=this.length;c<e;c++)if(f=this[c],
1===f.nodeType&&f.className)if(a){g=(" "+f.className+" ").replace(pb," ");h=0;for(i=b.length;h<i;h++)g=g.replace(" "+b[h]+" "," ");f.className=d.trim(g)}else f.className=""}return this},toggleClass:function(a,b){var c=typeof a,e="boolean"===typeof b;return d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,this.className,b),b)}):this.each(function(){if("string"===c)for(var f,g=0,h=d(this),i=b,j=a.split(ia);f=j[g++];)i=e?i:!h.hasClass(f),h[i?"addClass":"removeClass"](f);else if("undefined"===
c||"boolean"===c)this.className&&d._data(this,"__className__",this.className),this.className=this.className||!1===a?"":d._data(this,"__className__")||""})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&-1<(" "+this[b].className+" ").replace(pb," ").indexOf(a))return!0;return!1},val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(c){var f=d(this);if(1===this.nodeType&&(c=e?a.call(this,c,f.val()):a,null==c?
c="":"number"===typeof c?c+="":d.isArray(c)&&(c=d.map(c,function(a){return null==a?"":a+""})),b=d.valHooks[this.nodeName.toLowerCase()]||d.valHooks[this.type],!b||!("set"in b)||void 0===b.set(this,c,"value")))this.value=c});if(f){if((b=d.valHooks[f.nodeName.toLowerCase()]||d.valHooks[f.type])&&"get"in b&&void 0!==(c=b.get(f,"value")))return c;c=f.value;return"string"===typeof c?c.replace(vc,""):null==c?"":c}}});d.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?
a.value:a.text}},select:{get:function(a){var b,c,e=a.selectedIndex,f=[],g=a.options,h="select-one"===a.type;if(0>e)return null;a=h?e:0;for(c=h?e+1:g.length;a<c;a++)if(b=g[a],b.selected&&(d.support.optDisabled?!b.disabled:null===b.getAttribute("disabled"))&&(!b.parentNode.disabled||!d.nodeName(b.parentNode,"optgroup"))){b=d(b).val();if(h)return b;f.push(b)}return h&&!f.length&&g.length?d(g[e]).val():f},set:function(a,b){var c=d.makeArray(b);d(a).find("option").each(function(){this.selected=0<=d.inArray(d(this).val(),
c)});c.length||(a.selectedIndex=-1);return c}}},attrFn:{val:!0,css:!0,html:!0,text:!0,data:!0,width:!0,height:!0,offset:!0},attr:function(a,b,c,e){var f,g,h=a.nodeType;if(a&&!(3===h||8===h||2===h)){if(e&&b in d.attrFn)return d(a)[b](c);if("undefined"===typeof a.getAttribute)return d.prop(a,b,c);if(e=1!==h||!d.isXMLDoc(a))b=b.toLowerCase(),g=d.attrHooks[b]||(qb.test(b)?sb:w);if(void 0!==c)if(null===c)d.removeAttr(a,b);else{if(g&&"set"in g&&e&&void 0!==(f=g.set(a,c,b)))return f;a.setAttribute(b,""+
c);return c}else{if(g&&"get"in g&&e&&null!==(f=g.get(a,b)))return f;f=a.getAttribute(b);return null===f?void 0:f}}},removeAttr:function(a,b){var c,e,f,g,h=0;if(b&&1===a.nodeType){e=b.toLowerCase().split(ia);for(g=e.length;h<g;h++)if(f=e[h])c=d.propFix[f]||f,d.attr(a,f,""),a.removeAttribute(rb?f:c),qb.test(f)&&c in a&&(a[c]=!1)}},attrHooks:{type:{set:function(a,b){if(wc.test(a.nodeName)&&a.parentNode)d.error("type property can't be changed");else if(!d.support.radioValue&&"radio"===b&&d.nodeName(a,
"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}},value:{get:function(a,b){return w&&d.nodeName(a,"button")?w.get(a,b):b in a?a.value:null},set:function(a,b,c){if(w&&d.nodeName(a,"button"))return w.set(a,b,c);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},
prop:function(a,b,c){var e,f,g;g=a.nodeType;if(a&&!(3===g||8===g||2===g)){if(g=1!==g||!d.isXMLDoc(a))b=d.propFix[b]||b,f=d.propHooks[b];return void 0!==c?f&&"set"in f&&void 0!==(e=f.set(a,c,b))?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):xc.test(a.nodeName)||yc.test(a.nodeName)&&a.href?0:void 0}}}});d.attrHooks.tabindex=d.propHooks.tabIndex;sb={get:function(a,b){var c,e=d.prop(a,
b);return!0===e||"boolean"!==typeof e&&(c=a.getAttributeNode(b))&&!1!==c.nodeValue?b.toLowerCase():void 0},set:function(a,b,c){!1===b?d.removeAttr(a,c):(b=d.propFix[c]||c,b in a&&(a[b]=!0),a.setAttribute(c,c.toLowerCase()));return c}};rb||(tb={name:!0,id:!0},w=d.valHooks.button={get:function(a,b){var c;return(c=a.getAttributeNode(b))&&(tb[b]?""!==c.nodeValue:c.specified)?c.nodeValue:void 0},set:function(a,b,c){var e=a.getAttributeNode(c);e||(e=l.createAttribute(c),a.setAttributeNode(e));return e.nodeValue=
b+""}},d.attrHooks.tabindex.set=w.set,d.each(["width","height"],function(a,b){d.attrHooks[b]=d.extend(d.attrHooks[b],{set:function(a,e){if(""===e)return a.setAttribute(b,"auto"),e}})}),d.attrHooks.contenteditable={get:w.get,set:function(a,b,c){""===b&&(b="false");w.set(a,b,c)}});d.support.hrefNormalized||d.each(["href","src","width","height"],function(a,b){d.attrHooks[b]=d.extend(d.attrHooks[b],{get:function(a){a=a.getAttribute(b,2);return null===a?void 0:a}})});d.support.style||(d.attrHooks.style=
{get:function(a){return a.style.cssText.toLowerCase()||void 0},set:function(a,b){return a.style.cssText=""+b}});d.support.optSelected||(d.propHooks.selected=d.extend(d.propHooks.selected,{get:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex;return null}}));d.support.enctype||(d.propFix.enctype="encoding");d.support.checkOn||d.each(["radio","checkbox"],function(){d.valHooks[this]={get:function(a){return null===a.getAttribute("value")?"on":a.value}}});d.each(["radio",
"checkbox"],function(){d.valHooks[this]=d.extend(d.valHooks[this],{set:function(a,b){if(d.isArray(b))return a.checked=0<=d.inArray(d(a).val(),b)}})});var Fa=/^(?:textarea|input|select)$/i,ub=/^([^\.]*)?(?:\.(.+))?$/,zc=/\bhover(\.\S+)?\b/,Ac=/^key/,Bc=/^(?:mouse|contextmenu)|click/,vb=/^(?:focusinfocus|focusoutblur)$/,Cc=/^(\w*)(?:#([\w\-]+))?(?:\.([\w\-]+))?$/,Dc=function(a){if(a=Cc.exec(a))a[1]=(a[1]||"").toLowerCase(),a[3]=a[3]&&RegExp("(?:^|\\s)"+a[3]+"(?:\\s|$)");return a},wb=function(a){return d.event.special.hover?
a:a.replace(zc,"mouseenter$1 mouseleave$1")};d.event={add:function(a,b,c,e,f){var g,h,i,j,n,l,k,s,m;if(!(3===a.nodeType||8===a.nodeType||!b||!c||!(g=d._data(a)))){c.handler&&(k=c,c=k.handler);c.guid||(c.guid=d.guid++);i=g.events;i||(g.events=i={});h=g.handle;h||(g.handle=h=function(a){return"undefined"!==typeof d&&(!a||d.event.triggered!==a.type)?d.event.dispatch.apply(h.elem,arguments):void 0},h.elem=a);b=d.trim(wb(b)).split(" ");for(g=0;g<b.length;g++){j=ub.exec(b[g])||[];n=j[1];l=(j[2]||"").split(".").sort();
m=d.event.special[n]||{};n=(f?m.delegateType:m.bindType)||n;m=d.event.special[n]||{};j=d.extend({type:n,origType:j[1],data:e,handler:c,guid:c.guid,selector:f,quick:Dc(f),namespace:l.join(".")},k);s=i[n];if(!s&&(s=i[n]=[],s.delegateCount=0,!m.setup||!1===m.setup.call(a,e,l,h)))a.addEventListener?a.addEventListener(n,h,!1):a.attachEvent&&a.attachEvent("on"+n,h);m.add&&(m.add.call(a,j),j.handler.guid||(j.handler.guid=c.guid));f?s.splice(s.delegateCount++,0,j):s.push(j);d.event.global[n]=!0}a=null}},
global:{},remove:function(a,b,c,e,f){var g=d.hasData(a)&&d._data(a),h,i,j,n,l,k,s,m,o,p;if(g&&(s=g.events)){b=d.trim(wb(b||"")).split(" ");for(h=0;h<b.length;h++)if(i=ub.exec(b[h])||[],j=n=i[1],i=i[2],j){m=d.event.special[j]||{};j=(e?m.delegateType:m.bindType)||j;o=s[j]||[];l=o.length;i=i?RegExp("(^|\\.)"+i.split(".").sort().join("\\.(?:.*\\.)?")+"(\\.|$)"):null;for(k=0;k<o.length;k++)if(p=o[k],(f||n===p.origType)&&(!c||c.guid===p.guid)&&(!i||i.test(p.namespace))&&(!e||e===p.selector||"**"===e&&p.selector))o.splice(k--,
1),p.selector&&o.delegateCount--,m.remove&&m.remove.call(a,p);0===o.length&&l!==o.length&&((!m.teardown||!1===m.teardown.call(a,i))&&d.removeEvent(a,j,g.handle),delete s[j])}else for(j in s)d.event.remove(a,j+b[h],c,e,!0);if(d.isEmptyObject(s)){if(b=g.handle)b.elem=null;d.removeData(a,["events","handle"],!0)}}},customEvent:{getData:!0,setData:!0,changeData:!0},trigger:function(a,b,c,e){if(!c||!(3===c.nodeType||8===c.nodeType)){var f=a.type||a,g=[],h,i,j,n,l;if(!vb.test(f+d.event.triggered)&&(0<=f.indexOf("!")&&
(f=f.slice(0,-1),h=!0),0<=f.indexOf(".")&&(g=f.split("."),f=g.shift(),g.sort()),c&&!d.event.customEvent[f]||d.event.global[f]))if(a="object"===typeof a?a[d.expando]?a:new d.Event(f,a):new d.Event(f),a.type=f,a.isTrigger=!0,a.exclusive=h,a.namespace=g.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+g.join("\\.(?:.*\\.)?")+"(\\.|$)"):null,h=0>f.indexOf(":")?"on"+f:"",c){if(a.result=void 0,a.target||(a.target=c),b=null!=b?d.makeArray(b):[],b.unshift(a),j=d.event.special[f]||{},!(j.trigger&&!1===
j.trigger.apply(c,b))){l=[[c,j.bindType||f]];if(!e&&!j.noBubble&&!d.isWindow(c)){n=j.delegateType||f;g=vb.test(n+f)?c:c.parentNode;for(i=null;g;g=g.parentNode)l.push([g,n]),i=g;i&&i===c.ownerDocument&&l.push([i.defaultView||i.parentWindow||q,n])}for(i=0;i<l.length&&!a.isPropagationStopped();i++)g=l[i][0],a.type=l[i][1],(n=(d._data(g,"events")||{})[a.type]&&d._data(g,"handle"))&&n.apply(g,b),(n=h&&g[h])&&(d.acceptData(g)&&!1===n.apply(g,b))&&a.preventDefault();a.type=f;if(!e&&!a.isDefaultPrevented()&&
(!j._default||!1===j._default.apply(c.ownerDocument,b))&&!("click"===f&&d.nodeName(c,"a"))&&d.acceptData(c))if(h&&c[f]&&("focus"!==f&&"blur"!==f||0!==a.target.offsetWidth)&&!d.isWindow(c))(i=c[h])&&(c[h]=null),d.event.triggered=f,c[f](),d.event.triggered=void 0,i&&(c[h]=i);return a.result}}else for(i in c=d.cache,c)c[i].events&&c[i].events[f]&&d.event.trigger(a,b,c[i].handle.elem,!0)}},dispatch:function(a){a=d.event.fix(a||q.event);var b=(d._data(this,"events")||{})[a.type]||[],c=b.delegateCount,
e=[].slice.call(arguments,0),f=!a.exclusive&&!a.namespace,g=[],h,i,j,n,l,k,m;e[0]=a;a.delegateTarget=this;if(c&&!a.target.disabled&&!(a.button&&"click"===a.type)){j=d(this);j.context=this.ownerDocument||this;for(i=a.target;i!=this;i=i.parentNode||this){l={};k=[];j[0]=i;for(h=0;h<c;h++){n=b[h];m=n.selector;if(void 0===l[m]){var o=l,p=m,E;if(n.quick){E=n.quick;var r=i.attributes||{};E=(!E[1]||i.nodeName.toLowerCase()===E[1])&&(!E[2]||(r.id||{}).value===E[2])&&(!E[3]||E[3].test((r["class"]||{}).value))}else E=
j.is(m);o[p]=E}l[m]&&k.push(n)}k.length&&g.push({elem:i,matches:k})}}b.length>c&&g.push({elem:this,matches:b.slice(c)});for(h=0;h<g.length&&!a.isPropagationStopped();h++){c=g[h];a.currentTarget=c.elem;for(b=0;b<c.matches.length&&!a.isImmediatePropagationStopped();b++)if(n=c.matches[b],f||!a.namespace&&!n.namespace||a.namespace_re&&a.namespace_re.test(n.namespace))a.data=n.data,a.handleObj=n,n=((d.event.special[n.origType]||{}).handle||n.handler).apply(c.elem,e),void 0!==n&&(a.result=n,!1===n&&(a.preventDefault(),
a.stopPropagation()))}return a.result},props:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),
filter:function(a,b){var c,e,d=b.button,g=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||l,e=c.documentElement,c=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||c&&c.scrollLeft||0)-(e&&e.clientLeft||c&&c.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||c&&c.scrollTop||0)-(e&&e.clientTop||c&&c.clientTop||0));!a.relatedTarget&&g&&(a.relatedTarget=g===a.target?b.toElement:g);!a.which&&void 0!==d&&(a.which=d&1?1:d&2?3:d&4?2:0);return a}},fix:function(a){if(a[d.expando])return a;
var b,c,e=a,f=d.event.fixHooks[a.type]||{},g=f.props?this.props.concat(f.props):this.props;a=d.Event(e);for(b=g.length;b;)c=g[--b],a[c]=e[c];a.target||(a.target=e.srcElement||l);3===a.target.nodeType&&(a.target=a.target.parentNode);void 0===a.metaKey&&(a.metaKey=a.ctrlKey);return f.filter?f.filter(a,e):a},special:{ready:{setup:d.bindReady},load:{noBubble:!0},focus:{delegateType:"focusin"},blur:{delegateType:"focusout"},beforeunload:{setup:function(a,b,c){d.isWindow(this)&&(this.onbeforeunload=c)},
teardown:function(a,b){this.onbeforeunload===b&&(this.onbeforeunload=null)}}},simulate:function(a,b,c,e){a=d.extend(new d.Event,c,{type:a,isSimulated:!0,originalEvent:{}});e?d.event.trigger(a,null,b):d.event.dispatch.call(b,a);a.isDefaultPrevented()&&c.preventDefault()}};d.event.handle=d.event.dispatch;d.removeEvent=l.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)};d.Event=function(a,b){if(!(this instanceof
d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?$:L):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||d.now();this[d.expando]=!0};d.Event.prototype={preventDefault:function(){this.isDefaultPrevented=$;var a=this.originalEvent;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){this.isPropagationStopped=$;var a=
this.originalEvent;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=$;this.stopPropagation()},isDefaultPrevented:L,isPropagationStopped:L,isImmediatePropagationStopped:L};d.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e=a.relatedTarget,f=a.handleObj,g;if(!e||e!==this&&!d.contains(this,e))a.type=f.origType,g=f.handler.apply(this,
arguments),a.type=b;return g}}});d.support.submitBubbles||(d.event.special.submit={setup:function(){if(d.nodeName(this,"form"))return!1;d.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=d.nodeName(a,"input")||d.nodeName(a,"button")?a.form:void 0)&&!a._submit_attached)d.event.add(a,"submit._submit",function(a){this.parentNode&&!a.isTrigger&&d.event.simulate("submit",this.parentNode,a,!0)}),a._submit_attached=!0})},teardown:function(){if(d.nodeName(this,"form"))return!1;
d.event.remove(this,"._submit")}});d.support.changeBubbles||(d.event.special.change={setup:function(){if(Fa.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)d.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&(this._just_changed=!0)}),d.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1,d.event.simulate("change",this,a,!0))});return!1}d.event.add(this,"beforeactivate._change",function(a){a=
a.target;Fa.test(a.nodeName)&&!a._change_attached&&(d.event.add(a,"change._change",function(a){this.parentNode&&(!a.isSimulated&&!a.isTrigger)&&d.event.simulate("change",this.parentNode,a,!0)}),a._change_attached=!0)})},handle:function(a){var b=a.target;if(this!==b||a.isSimulated||a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){d.event.remove(this,"._change");return Fa.test(this.nodeName)}});d.support.focusinBubbles||d.each({focus:"focusin",
blur:"focusout"},function(a,b){var c=0,e=function(a){d.event.simulate(b,a.target,d.event.fix(a),!0)};d.event.special[b]={setup:function(){0===c++&&l.addEventListener(a,e,!0)},teardown:function(){0===--c&&l.removeEventListener(a,e,!0)}}});d.fn.extend({on:function(a,b,c,e,f){var g,h;if("object"===typeof a){"string"!==typeof b&&(c=b,b=void 0);for(h in a)this.on(h,b,c,a[h],f);return this}null==c&&null==e?(e=b,c=b=void 0):null==e&&("string"===typeof b?(e=c,c=void 0):(e=c,c=b,b=void 0));if(!1===e)e=L;else if(!e)return this;
1===f&&(g=e,e=function(a){d().off(a);return g.apply(this,arguments)},e.guid=g.guid||(g.guid=d.guid++));return this.each(function(){d.event.add(this,a,e,c,b)})},one:function(a,b,c,e){return this.on.call(this,a,b,c,e,1)},off:function(a,b,c){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;d(a.delegateTarget).off(e.namespace?e.type+"."+e.namespace:e.type,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=void 0;
!1===c&&(c=L);return this.each(function(){d.event.remove(this,a,c,b)})},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,c){d(this.context).on(a,this.selector,b,c);return this},die:function(a,b){d(this.context).off(a,this.selector||"**",b);return this},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1==arguments.length?this.off(a,"**"):this.off(b,a,c)},trigger:function(a,b){return this.each(function(){d.event.trigger(a,
b,this)})},triggerHandler:function(a,b){if(this[0])return d.event.trigger(a,b,this[0],!0)},toggle:function(a){var b=arguments,c=a.guid||d.guid++,e=0,f=function(c){var f=(d._data(this,"lastToggle"+a.guid)||0)%e;d._data(this,"lastToggle"+a.guid,f+1);c.preventDefault();return b[f].apply(this,arguments)||!1};for(f.guid=c;e<b.length;)b[e++].guid=c;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,e){null==e&&(e=a,a=null);return 0<arguments.length?this.on(b,null,a,e):this.trigger(b)};d.attrFn&&(d.attrFn[b]=!0);Ac.test(b)&&(d.event.fixHooks[b]=d.event.keyHooks);Bc.test(b)&&(d.event.fixHooks[b]=d.event.mouseHooks)});var xb=function(a,b,c,e,d,g){d=0;for(var h=e.length;d<h;d++){var i=e[d];if(i){for(var j=!1,i=i[a];i;){if(i[S]===c){j=e[i.sizset];break}1===i.nodeType&&!g&&(i[S]=c,i.sizset=d);if(i.nodeName.toLowerCase()===b){j=i;break}i=i[a]}e[d]=j}}},yb=function(a,
b,c,e,d,g){d=0;for(var h=e.length;d<h;d++){var i=e[d];if(i){for(var j=!1,i=i[a];i;){if(i[S]===c){j=e[i.sizset];break}if(1===i.nodeType)if(g||(i[S]=c,i.sizset=d),"string"!==typeof b){if(i===b){j=!0;break}}else if(0<m.filter(b,[i]).length){j=i;break}i=i[a]}e[d]=j}}},Ga=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,S="sizcache"+(Math.random()+"").replace(".",""),Ha=0,zb=Object.prototype.toString,ja=!1,Ab=!0,T=/\\/g,
Ec=/\r\n/g,ka=/\W/;[0,0].sort(function(){Ab=!1;return 0});var m=function(a,b,c,e){c=c||[];var d=b=b||l;if(1!==b.nodeType&&9!==b.nodeType)return[];if(!a||"string"!==typeof a)return c;var g,h,i,j,n,k=!0,o=m.isXML(b),s=[],q=a;do if(Ga.exec(""),g=Ga.exec(q))if(q=g[3],s.push(g[1]),g[2]){j=g[3];break}while(g);if(1<s.length&&Fc.exec(a))if(2===s.length&&p.relative[s[0]])h=Bb(s[0]+s[1],b,e);else for(h=p.relative[s[0]]?[b]:m(s.shift(),b);s.length;)a=s.shift(),p.relative[a]&&(a+=s.shift()),h=Bb(a,h,e);else if(!e&&
(1<s.length&&9===b.nodeType&&!o&&p.match.ID.test(s[0])&&!p.match.ID.test(s[s.length-1]))&&(g=m.find(s.shift(),b,o),b=g.expr?m.filter(g.expr,g.set)[0]:g.set[0]),b){g=e?{expr:s.pop(),set:x(e)}:m.find(s.pop(),1===s.length&&("~"===s[0]||"+"===s[0])&&b.parentNode?b.parentNode:b,o);h=g.expr?m.filter(g.expr,g.set):g.set;for(0<s.length?i=x(h):k=!1;s.length;)g=n=s.pop(),p.relative[n]?g=s.pop():n="",null==g&&(g=b),p.relative[n](i,g,o)}else i=[];i||(i=h);i||m.error(n||a);if("[object Array]"===zb.call(i))if(k)if(b&&
1===b.nodeType)for(a=0;null!=i[a];a++)i[a]&&(!0===i[a]||1===i[a].nodeType&&m.contains(b,i[a]))&&c.push(h[a]);else for(a=0;null!=i[a];a++)i[a]&&1===i[a].nodeType&&c.push(h[a]);else c.push.apply(c,i);else x(i,c);j&&(m(j,d,c,e),m.uniqueSort(c));return c};m.uniqueSort=function(a){if(la&&(ja=Ab,a.sort(la),ja))for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1);return a};m.matches=function(a,b){return m(a,null,null,b)};m.matchesSelector=function(a,b){return 0<m(b,null,null,[a]).length};m.find=function(a,
b,c){var e,d,g,h,i,j;if(!a)return[];d=0;for(g=p.order.length;d<g;d++)if(i=p.order[d],h=p.leftMatch[i].exec(a))if(j=h[1],h.splice(1,1),"\\"!==j.substr(j.length-1)&&(h[1]=(h[1]||"").replace(T,""),e=p.find[i](h,b,c),null!=e)){a=a.replace(p.match[i],"");break}e||(e="undefined"!==typeof b.getElementsByTagName?b.getElementsByTagName("*"):[]);return{set:e,expr:a}};m.filter=function(a,b,c,e){for(var d,g,h,i,j,n,l,k,o=a,q=[],r=b,E=b&&b[0]&&m.isXML(b[0]);a&&b.length;){for(h in p.filter)if(null!=(d=p.leftMatch[h].exec(a))&&
d[2])if(n=p.filter[h],j=d[1],g=!1,d.splice(1,1),"\\"!==j.substr(j.length-1)){r===q&&(q=[]);if(p.preFilter[h])if(d=p.preFilter[h](d,r,c,q,e,E)){if(!0===d)continue}else g=i=!0;if(d)for(l=0;null!=(j=r[l]);l++)j&&(i=n(j,d,l,r),k=e^i,c&&null!=i?k?g=!0:r[l]=!1:k&&(q.push(j),g=!0));if(void 0!==i){c||(r=q);a=a.replace(p.match[h],"");if(!g)return[];break}}if(a===o)if(null==g)m.error(a);else break;o=a}return r};m.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};var Ia=m.getText=
function(a){var b,c;b=a.nodeType;var d="";if(b)if(1===b||9===b){if("string"===typeof a.textContent)return a.textContent;if("string"===typeof a.innerText)return a.innerText.replace(Ec,"");for(a=a.firstChild;a;a=a.nextSibling)d+=Ia(a)}else{if(3===b||4===b)return a.nodeValue}else for(b=0;c=a[b];b++)8!==c.nodeType&&(d+=Ia(c));return d},p=m.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,
ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")},
type:function(a){return a.getAttribute("type")}},relative:{"+":function(a,b){var c="string"===typeof b,d=c&&!ka.test(b),c=c&&!d;d&&(b=b.toLowerCase());for(var d=0,f=a.length,g;d<f;d++)if(g=a[d]){for(;(g=g.previousSibling)&&1!==g.nodeType;);a[d]=c||g&&g.nodeName.toLowerCase()===b?g||!1:g===b}c&&m.filter(b,a,!0)},"\x3e":function(a,b){var c,d="string"===typeof b,f=0,g=a.length;if(d&&!ka.test(b))for(b=b.toLowerCase();f<g;f++){if(c=a[f])c=c.parentNode,a[f]=c.nodeName.toLowerCase()===b?c:!1}else{for(;f<
g;f++)(c=a[f])&&(a[f]=d?c.parentNode:c.parentNode===b);d&&m.filter(b,a,!0)}},"":function(a,b,c){var d,f=Ha++,g=yb;"string"===typeof b&&!ka.test(b)&&(d=b=b.toLowerCase(),g=xb);g("parentNode",b,f,a,d,c)},"~":function(a,b,c){var d,f=Ha++,g=yb;"string"===typeof b&&!ka.test(b)&&(d=b=b.toLowerCase(),g=xb);g("previousSibling",b,f,a,d,c)}},find:{ID:function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,b){if("undefined"!==typeof b.getElementsByName){for(var c=
[],d=b.getElementsByName(a[1]),f=0,g=d.length;f<g;f++)d[f].getAttribute("name")===a[1]&&c.push(d[f]);return 0===c.length?null:c}},TAG:function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,d,f,g){a=" "+a[1].replace(T,"")+" ";if(g)return a;g=0;for(var h;null!=(h=b[g]);g++)h&&(f^(h.className&&0<=(" "+h.className+" ").replace(/[\t\n\r]/g," ").indexOf(a))?c||d.push(h):c&&(b[g]=!1));return!1},ID:function(a){return a[1].replace(T,
"")},TAG:function(a){return a[1].replace(T,"").toLowerCase()},CHILD:function(a){if("nth"===a[1]){a[2]||m.error(a[0]);a[2]=a[2].replace(/^\+|\s*/g,"");var b=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===a[2]&&"2n"||"odd"===a[2]&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}else a[2]&&m.error(a[0]);a[0]=Ha++;return a},ATTR:function(a,b,c,d,f,g){b=a[1]=a[1].replace(T,"");!g&&p.attrMap[b]&&(a[1]=p.attrMap[b]);a[4]=(a[4]||a[5]||"").replace(T,"");"~\x3d"===a[2]&&(a[4]=" "+
a[4]+" ");return a},PSEUDO:function(a,b,c,d,f){if("not"===a[1])if(1<(Ga.exec(a[3])||"").length||/^\w/.test(a[3]))a[3]=m(a[3],null,null,b);else return a=m.filter(a[3],b,c,1^f),c||d.push.apply(d,a),!1;else if(p.match.POS.test(a[0])||p.match.CHILD.test(a[0]))return!0;return a},POS:function(a){a.unshift(!0);return a}},filters:{enabled:function(a){return!1===a.disabled&&"hidden"!==a.type},disabled:function(a){return!0===a.disabled},checked:function(a){return!0===a.checked},selected:function(a){a.parentNode&&
a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(a,b,c){return!!m(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){var b=a.getAttribute("type"),c=a.type;return"input"===a.nodeName.toLowerCase()&&"text"===c&&(b===c||null===b)},radio:function(a){return"input"===a.nodeName.toLowerCase()&&"radio"===a.type},checkbox:function(a){return"input"===a.nodeName.toLowerCase()&&"checkbox"===
a.type},file:function(a){return"input"===a.nodeName.toLowerCase()&&"file"===a.type},password:function(a){return"input"===a.nodeName.toLowerCase()&&"password"===a.type},submit:function(a){var b=a.nodeName.toLowerCase();return("input"===b||"button"===b)&&"submit"===a.type},image:function(a){return"input"===a.nodeName.toLowerCase()&&"image"===a.type},reset:function(a){var b=a.nodeName.toLowerCase();return("input"===b||"button"===b)&&"reset"===a.type},button:function(a){var b=a.nodeName.toLowerCase();
return"input"===b&&"button"===a.type||"button"===b},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)},focus:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b){return 0===b},last:function(a,b,c,d){return b===d.length-1},even:function(a,b){return 0===b%2},odd:function(a,b){return 1===b%2},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-0===b}},filter:{PSEUDO:function(a,
b,c,d){var f=b[1],g=p.filters[f];if(g)return g(a,c,b,d);if("contains"===f)return 0<=(a.textContent||a.innerText||Ia([a])||"").indexOf(b[3]);if("not"===f){b=b[3];c=0;for(d=b.length;c<d;c++)if(b[c]===a)return!1;return!0}m.error(f)},CHILD:function(a,b){var c,d,f,g,h,i;c=b[1];i=a;switch(c){case "only":case "first":for(;i=i.previousSibling;)if(1===i.nodeType)return!1;if("first"===c)return!0;i=a;case "last":for(;i=i.nextSibling;)if(1===i.nodeType)return!1;return!0;case "nth":c=b[2];d=b[3];if(1===c&&0===
d)return!0;f=b[0];if((g=a.parentNode)&&(g[S]!==f||!a.nodeIndex)){h=0;for(i=g.firstChild;i;i=i.nextSibling)1===i.nodeType&&(i.nodeIndex=++h);g[S]=f}i=a.nodeIndex-d;return 0===c?0===i:0===i%c&&0<=i/c}},ID:function(a,b){return 1===a.nodeType&&a.getAttribute("id")===b},TAG:function(a,b){return"*"===b&&1===a.nodeType||!!a.nodeName&&a.nodeName.toLowerCase()===b},CLASS:function(a,b){return-1<(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)},ATTR:function(a,b){var c=b[1],c=m.attr?m.attr(a,c):p.attrHandle[c]?
p.attrHandle[c](a):null!=a[c]?a[c]:a.getAttribute(c),d=c+"",f=b[2],g=b[4];return null==c?"!\x3d"===f:!f&&m.attr?null!=c:"\x3d"===f?d===g:"*\x3d"===f?0<=d.indexOf(g):"~\x3d"===f?0<=(" "+d+" ").indexOf(g):!g?d&&!1!==c:"!\x3d"===f?d!==g:"^\x3d"===f?0===d.indexOf(g):"$\x3d"===f?d.substr(d.length-g.length)===g:"|\x3d"===f?d===g||d.substr(0,g.length+1)===g+"-":!1},POS:function(a,b,c,d){var f=p.setFilters[b[2]];if(f)return f(a,c,b,d)}}},Fc=p.match.POS,Gc=function(a,b){return"\\"+(b-0+1)},Y;for(Y in p.match)p.match[Y]=
RegExp(p.match[Y].source+/(?![^\[]*\])(?![^\(]*\))/.source),p.leftMatch[Y]=RegExp(/(^(?:.|\r|\n)*?)/.source+p.match[Y].source.replace(/\\(\d+)/g,Gc));var x=function(a,b){a=Array.prototype.slice.call(a,0);return b?(b.push.apply(b,a),b):a};try{Array.prototype.slice.call(l.documentElement.childNodes,0)[0].nodeType}catch(md){x=function(a,b){var c=0,d=b||[];if("[object Array]"===zb.call(a))Array.prototype.push.apply(d,a);else if("number"===typeof a.length)for(var f=a.length;c<f;c++)d.push(a[c]);else for(;a[c];c++)d.push(a[c]);
return d}}var la,Z;l.documentElement.compareDocumentPosition?la=function(a,b){return a===b?(ja=!0,0):!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1}:(la=function(a,b){if(a===b)return ja=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,d,f=[],g=[];c=a.parentNode;d=b.parentNode;var h=c;if(c===d)return Z(a,b);if(c){if(!d)return 1}else return-1;for(;h;)f.unshift(h),h=h.parentNode;for(h=d;h;)g.unshift(h),
h=h.parentNode;c=f.length;d=g.length;for(h=0;h<c&&h<d;h++)if(f[h]!==g[h])return Z(f[h],g[h]);return h===c?Z(a,g[h],-1):Z(f[h],b,1)},Z=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});var ma=l.createElement("div"),Cb="script"+(new Date).getTime(),na=l.documentElement;ma.innerHTML="\x3ca name\x3d'"+Cb+"'/\x3e";na.insertBefore(ma,na.firstChild);l.getElementById(Cb)&&(p.find.ID=function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(b=
b.getElementById(a[1]))?b.id===a[1]||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").nodeValue===a[1]?[b]:void 0:[]},p.filter.ID=function(a,b){var c="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id");return 1===a.nodeType&&c&&c.nodeValue===b});na.removeChild(ma);var na=ma=null,J=l.createElement("div");J.appendChild(l.createComment(""));0<J.getElementsByTagName("*").length&&(p.find.TAG=function(a,b){var c=b.getElementsByTagName(a[1]);if("*"===a[1]){for(var d=[],f=0;c[f];f++)1===
c[f].nodeType&&d.push(c[f]);c=d}return c});J.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";J.firstChild&&("undefined"!==typeof J.firstChild.getAttribute&&"#"!==J.firstChild.getAttribute("href"))&&(p.attrHandle.href=function(a){return a.getAttribute("href",2)});J=null;if(l.querySelectorAll){var Ja=m,oa=l.createElement("div");oa.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(oa.querySelectorAll&&0===oa.querySelectorAll(".TEST").length)){var m=function(a,b,c,d){b=b||l;if(!d&&!m.isXML(b)){var f=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(a);
if(f&&(1===b.nodeType||9===b.nodeType)){if(f[1])return x(b.getElementsByTagName(a),c);if(f[2]&&p.find.CLASS&&b.getElementsByClassName)return x(b.getElementsByClassName(f[2]),c)}if(9===b.nodeType){if("body"===a&&b.body)return x([b.body],c);if(f&&f[3]){var g=b.getElementById(f[3]);if(g&&g.parentNode){if(g.id===f[3])return x([g],c)}else return x([],c)}try{return x(b.querySelectorAll(a),c)}catch(h){}}else if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){var f=b,i=(g=b.getAttribute("id"))||"__sizzle__",
j=b.parentNode,n=/^\s*[+~]/.test(a);g?i=i.replace(/'/g,"\\$\x26"):b.setAttribute("id",i);n&&j&&(b=b.parentNode);try{if(!n||j)return x(b.querySelectorAll("[id\x3d'"+i+"'] "+a),c)}catch(k){}finally{g||f.removeAttribute("id")}}}return Ja(a,b,c,d)},Ka;for(Ka in Ja)m[Ka]=Ja[Ka];oa=null}}var pa=l.documentElement,qa=pa.matchesSelector||pa.mozMatchesSelector||pa.webkitMatchesSelector||pa.msMatchesSelector;if(qa){var Hc=!qa.call(l.createElement("div"),"div"),Db=!1;try{qa.call(l.documentElement,"[test!\x3d'']:sizzle")}catch(nd){Db=
!0}m.matchesSelector=function(a,b){b=b.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!m.isXML(a))try{if(Db||!p.match.PSEUDO.test(b)&&!/!=/.test(b)){var c=qa.call(a,b);if(c||!Hc||a.document&&11!==a.document.nodeType)return c}}catch(d){}return 0<m(b,null,null,[a]).length}}var U=l.createElement("div");U.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";U.getElementsByClassName&&0!==U.getElementsByClassName("e").length&&(U.lastChild.className="e",1!==U.getElementsByClassName("e").length&&
(p.order.splice(1,0,"CLASS"),p.find.CLASS=function(a,b,c){if("undefined"!==typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a[1])},U=null));m.contains=l.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:l.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return!1};m.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1};var Bb=function(a,b,c){var d,f=
[],g="";for(b=b.nodeType?[b]:b;d=p.match.PSEUDO.exec(a);)g+=d[0],a=a.replace(p.match.PSEUDO,"");a=p.relative[a]?a+"*":a;d=0;for(var h=b.length;d<h;d++)m(a,b[d],f,c);return m.filter(g,f)};m.attr=d.attr;m.selectors.attrMap={};d.find=m;d.expr=m.selectors;d.expr[":"]=d.expr.filters;d.unique=m.uniqueSort;d.text=m.getText;d.isXMLDoc=m.isXML;d.contains=m.contains;var Ic=/Until$/,Jc=/^(?:parents|prevUntil|prevAll)/,Kc=/,/,Wb=/^.[^:#\[\.,]*$/,Lc=Array.prototype.slice,Eb=d.expr.match.POS,Mc={children:!0,contents:!0,
next:!0,prev:!0};d.fn.extend({find:function(a){var b=this,c,e;if("string"!==typeof a)return d(a).filter(function(){c=0;for(e=b.length;c<e;c++)if(d.contains(b[c],this))return!0});var f=this.pushStack("","find",a),g,h,i;c=0;for(e=this.length;c<e;c++)if(g=f.length,d.find(a,this[c],f),0<c)for(h=g;h<f.length;h++)for(i=0;i<g;i++)if(f[i]===f[h]){f.splice(h--,1);break}return f},has:function(a){var b=d(a);return this.filter(function(){for(var a=0,e=b.length;a<e;a++)if(d.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(Ra(this,
a,!1),"not",a)},filter:function(a){return this.pushStack(Ra(this,a,!0),"filter",a)},is:function(a){return!!a&&("string"===typeof a?Eb.test(a)?0<=d(a,this.context).index(this[0]):0<d.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){var c=[],e,f,g=this[0];if(d.isArray(a)){for(f=1;g&&g.ownerDocument&&g!==b;){for(e=0;e<a.length;e++)d(g).is(a[e])&&c.push({selector:a[e],elem:g,level:f});g=g.parentNode;f++}return c}var h=Eb.test(a)||"string"!==typeof a?d(a,b||this.context):0;e=0;for(f=
this.length;e<f;e++)for(g=this[e];g;)if(h?-1<h.index(g):d.find.matchesSelector(g,a)){c.push(g);break}else if(g=g.parentNode,!g||!g.ownerDocument||g===b||11===g.nodeType)break;c=1<c.length?d.unique(c):c;return this.pushStack(c,"closest",a)},index:function(a){return!a?this[0]&&this[0].parentNode?this.prevAll().length:-1:"string"===typeof a?d.inArray(this[0],d(a)):d.inArray(a.jquery?a[0]:a,this)},add:function(a,b){var c="string"===typeof a?d(a,b):d.makeArray(a&&a.nodeType?[a]:a),e=d.merge(this.get(),
c);return this.pushStack(!c[0]||!c[0].parentNode||11===c[0].parentNode.nodeType||!e[0]||!e[0].parentNode||11===e[0].parentNode.nodeType?e:d.unique(e))},andSelf:function(){return this.add(this.prevObject)}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return d.dir(a,"parentNode")},parentsUntil:function(a,b,c){return d.dir(a,"parentNode",c)},next:function(a){return d.nth(a,2,"nextSibling")},prev:function(a){return d.nth(a,2,"previousSibling")},nextAll:function(a){return d.dir(a,
"nextSibling")},prevAll:function(a){return d.dir(a,"previousSibling")},nextUntil:function(a,b,c){return d.dir(a,"nextSibling",c)},prevUntil:function(a,b,c){return d.dir(a,"previousSibling",c)},siblings:function(a){return d.sibling(a.parentNode.firstChild,a)},children:function(a){return d.sibling(a.firstChild)},contents:function(a){return d.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:d.makeArray(a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);Ic.test(a)||
(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));f=1<this.length&&!Mc[a]?d.unique(f):f;if((1<this.length||Kc.test(e))&&Jc.test(a))f=f.reverse();return this.pushStack(f,a,Lc.call(arguments).join(","))}});d.extend({filter:function(a,b,c){c&&(a=":not("+a+")");return 1===b.length?d.find.matchesSelector(b[0],a)?[b[0]]:[]:d.find.matches(a,b)},dir:function(a,b,c){var e=[];for(a=a[b];a&&9!==a.nodeType&&(void 0===c||1!==a.nodeType||!d(a).is(c));)1===a.nodeType&&e.push(a),a=a[b];return e},nth:function(a,b,c){b=
b||1;for(var d=0;a&&!(1===a.nodeType&&++d===b);a=a[c]);return a},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var Ta="abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",Nc=/ jQuery\d+="(?:\d+|null)"/g,La=/^\s+/,Fb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Gb=/<([\w:]+)/,Oc=/<tbody/i,Pc=/<|&#?\w+;/,Qc=/<(?:script|style)/i,
Rc=/<(?:script|object|embed|option|style)/i,Hb=RegExp("\x3c(?:"+Ta+")","i"),Ib=/checked\s*(?:[^=]|=\s*.checked.)/i,Sc=/\/(java|ecma)script/i,Yb=/^\s*<!(?:\[CDATA\[|\-\-)/,y={option:[1,"\x3cselect multiple\x3d'multiple'\x3e","\x3c/select\x3e"],legend:[1,"\x3cfieldset\x3e","\x3c/fieldset\x3e"],thead:[1,"\x3ctable\x3e","\x3c/table\x3e"],tr:[2,"\x3ctable\x3e\x3ctbody\x3e","\x3c/tbody\x3e\x3c/table\x3e"],td:[3,"\x3ctable\x3e\x3ctbody\x3e\x3ctr\x3e","\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e"],col:[2,"\x3ctable\x3e\x3ctbody\x3e\x3c/tbody\x3e\x3ccolgroup\x3e",
"\x3c/colgroup\x3e\x3c/table\x3e"],area:[1,"\x3cmap\x3e","\x3c/map\x3e"],_default:[0,"",""]},Jb=Sa(l);y.optgroup=y.option;y.tbody=y.tfoot=y.colgroup=y.caption=y.thead;y.th=y.td;d.support.htmlSerialize||(y._default=[1,"div\x3cdiv\x3e","\x3c/div\x3e"]);d.fn.extend({text:function(a){return d.isFunction(a)?this.each(function(b){var c=d(this);c.text(a.call(this,b,c.text()))}):"object"!==typeof a&&void 0!==a?this.empty().append((this[0]&&this[0].ownerDocument||l).createTextNode(a)):d.text(this)},wrapAll:function(a){if(d.isFunction(a))return this.each(function(b){d(this).wrapAll(a.call(this,
b))});if(this[0]){var b=d(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?
a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){1===this.nodeType&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,
this)});if(arguments.length){var a=d.clean(arguments);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,d.clean(arguments));return a}},remove:function(a,b){for(var c=0,e;null!=(e=this[c]);c++)if(!a||d.filter(a,[e]).length)!b&&1===e.nodeType&&(d.cleanData(e.getElementsByTagName("*")),
d.cleanData([e])),e.parentNode&&e.parentNode.removeChild(e);return this},empty:function(){for(var a=0,b;null!=(b=this[a]);a++)for(1===b.nodeType&&d.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,b)})},html:function(a){if(void 0===a)return this[0]&&1===this[0].nodeType?this[0].innerHTML.replace(Nc,""):null;if("string"===typeof a&&!Qc.test(a)&&(d.support.leadingWhitespace||
!La.test(a))&&!y[(Gb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Fb,"\x3c$1\x3e\x3c/$2\x3e");try{for(var b=0,c=this.length;b<c;b++)1===this[b].nodeType&&(d.cleanData(this[b].getElementsByTagName("*")),this[b].innerHTML=a)}catch(e){this.empty().append(a)}}else d.isFunction(a)?this.each(function(b){var c=d(this);c.html(a.call(this,b,c.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(d.isFunction(a))return this.each(function(b){var c=d(this),
e=c.html();c.replaceWith(a.call(this,b,e))});"string"!==typeof a&&(a=d(a).detach());return this.each(function(){var b=this.nextSibling,c=this.parentNode;d(this).remove();b?d(b).before(a):d(c).append(a)})}return this.length?this.pushStack(d(d.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,c){var e,f,g,h=a[0],i=[];if(!d.support.checkClone&&3===arguments.length&&"string"===typeof h&&Ib.test(h))return this.each(function(){d(this).domManip(a,
b,c,!0)});if(d.isFunction(h))return this.each(function(e){var f=d(this);a[0]=h.call(this,e,b?f.html():void 0);f.domManip(a,b,c)});if(this[0]){e=h&&h.parentNode;e=d.support.parentNode&&e&&11===e.nodeType&&e.childNodes.length===this.length?{fragment:e}:d.buildFragment(a,this,i);g=e.fragment;if(f=1===g.childNodes.length?g=g.firstChild:g.firstChild){b=b&&d.nodeName(f,"tr");f=0;for(var j=this.length,n=j-1;f<j;f++)c.call(b?d.nodeName(this[f],"table")?this[f].getElementsByTagName("tbody")[0]||this[f].appendChild(this[f].ownerDocument.createElement("tbody")):
this[f]:this[f],e.cacheable||1<j&&f<n?d.clone(g,!0,!0):g)}i.length&&d.each(i,Xb)}return this}});d.buildFragment=function(a,b,c){var e,f,g,h,i=a[0];b&&b[0]&&(h=b[0].ownerDocument||b[0]);h.createDocumentFragment||(h=l);if(1===a.length&&"string"===typeof i&&512>i.length&&h===l&&"\x3c"===i.charAt(0)&&!Rc.test(i)&&(d.support.checkClone||!Ib.test(i))&&(d.support.html5Clone||!Hb.test(i)))f=!0,(g=d.fragments[i])&&1!==g&&(e=g);e||(e=h.createDocumentFragment(),d.clean(a,h,e,c));f&&(d.fragments[i]=g?e:1);return{fragment:e,
cacheable:f}};d.fragments={};d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(c){var e=[];c=d(c);var f=1===this.length&&this[0].parentNode;if(f&&11===f.nodeType&&1===f.childNodes.length&&1===c.length)return c[b](this[0]),this;for(var f=0,g=c.length;f<g;f++){var h=(0<f?this.clone(!0):this).get();d(c[f])[b](h);e=e.concat(h)}return this.pushStack(e,a,c.selector)}});d.extend({clone:function(a,b,c){var e,f,
g;d.support.html5Clone||!Hb.test("\x3c"+a.nodeName)?e=a.cloneNode(!0):(e=l.createElement("div"),Jb.appendChild(e),e.innerHTML=a.outerHTML,e=e.firstChild);var h=e;if((!d.support.noCloneEvent||!d.support.noCloneChecked)&&(1===a.nodeType||11===a.nodeType)&&!d.isXMLDoc(a)){Va(a,h);e=aa(a);f=aa(h);for(g=0;e[g];++g)f[g]&&Va(e[g],f[g])}if(b&&(Ua(a,h),c)){e=aa(a);f=aa(h);for(g=0;e[g];++g)Ua(e[g],f[g])}return h},clean:function(a,b,c,e){b=b||l;"undefined"===typeof b.createElement&&(b=b.ownerDocument||b[0]&&
b[0].ownerDocument||l);for(var f=[],g,h=0,i;null!=(i=a[h]);h++)if("number"===typeof i&&(i+=""),i){if("string"===typeof i)if(Pc.test(i)){i=i.replace(Fb,"\x3c$1\x3e\x3c/$2\x3e");g=(Gb.exec(i)||["",""])[1].toLowerCase();var j=y[g]||y._default,n=j[0],k=b.createElement("div");b===l?Jb.appendChild(k):Sa(b).appendChild(k);for(k.innerHTML=j[1]+i+j[2];n--;)k=k.lastChild;if(!d.support.tbody){n=Oc.test(i);j="table"===g&&!n?k.firstChild&&k.firstChild.childNodes:"\x3ctable\x3e"===j[1]&&!n?k.childNodes:[];for(g=
j.length-1;0<=g;--g)d.nodeName(j[g],"tbody")&&!j[g].childNodes.length&&j[g].parentNode.removeChild(j[g])}!d.support.leadingWhitespace&&La.test(i)&&k.insertBefore(b.createTextNode(La.exec(i)[0]),k.firstChild);i=k.childNodes}else i=b.createTextNode(i);var m;if(!d.support.appendChecked)if(i[0]&&"number"===typeof(m=i.length))for(g=0;g<m;g++)Xa(i[g]);else Xa(i);i.nodeType?f.push(i):f=d.merge(f,i)}if(c){a=function(a){return!a.type||Sc.test(a.type)};for(h=0;f[h];h++)e&&d.nodeName(f[h],"script")&&(!f[h].type||
"text/javascript"===f[h].type.toLowerCase())?e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]):(1===f[h].nodeType&&(b=d.grep(f[h].getElementsByTagName("script"),a),f.splice.apply(f,[h+1,0].concat(b))),c.appendChild(f[h]))}return f},cleanData:function(a){for(var b,c,e=d.cache,f=d.event.special,g=d.support.deleteExpando,h=0,i;null!=(i=a[h]);h++)if(!i.nodeName||!d.noData[i.nodeName.toLowerCase()])if(c=i[d.expando]){if((b=e[c])&&b.events){for(var j in b.events)f[j]?d.event.remove(i,j):d.removeEvent(i,
j,b.handle);b.handle&&(b.handle.elem=null)}g?delete i[d.expando]:i.removeAttribute&&i.removeAttribute(d.expando);delete e[c]}}});var Ma=/alpha\([^)]*\)/i,Tc=/opacity=([^)]*)/,Uc=/([A-Z]|^ms)/g,Kb=/^-?\d+(?:px)?$/i,Vc=/^-?\d/,Wc=/^([\-+])=([\-+.\de]+)/,Xc={position:"absolute",visibility:"hidden",display:"block"},Zb=["Left","Right"],$b=["Top","Bottom"],G,Lb,Mb;d.fn.css=function(a,b){return 2===arguments.length&&void 0===b?this:d.access(this,a,b,!0,function(a,b,f){return void 0!==f?d.style(a,b,f):d.css(a,
b)})};d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=G(a,"opacity","opacity");return""===c?"1":c}return a.style.opacity}}},cssNumber:{fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":d.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,c,e){if(a&&!(3===a.nodeType||8===a.nodeType||!a.style)){var f,g=d.camelCase(b),h=a.style,i=d.cssHooks[g];b=d.cssProps[g]||g;if(void 0!==c){e=typeof c;if("string"===e&&(f=Wc.exec(c)))c=
+(f[1]+1)*+f[2]+parseFloat(d.css(a,b)),e="number";if(!(null==c||"number"===e&&isNaN(c)))if("number"===e&&!d.cssNumber[g]&&(c+="px"),!i||!("set"in i)||void 0!==(c=i.set(a,c)))try{h[b]=c}catch(j){}}else return i&&"get"in i&&void 0!==(f=i.get(a,!1,e))?f:h[b]}},css:function(a,b,c){var e,f;b=d.camelCase(b);f=d.cssHooks[b];b=d.cssProps[b]||b;"cssFloat"===b&&(b="float");if(f&&"get"in f&&void 0!==(e=f.get(a,!0,c)))return e;if(G)return G(a,b)},swap:function(a,b,c){var d={},f;for(f in b)d[f]=a.style[f],a.style[f]=
b[f];c.call(a);for(f in b)a.style[f]=d[f]}});d.curCSS=d.css;d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){var g;if(e){if(0!==a.offsetWidth)return Ya(a,b,f);d.swap(a,Xc,function(){g=Ya(a,b,f)});return g}},set:function(a,b){if(Kb.test(b)){if(b=parseFloat(b),0<=b)return b+"px"}else return b}}});d.support.opacity||(d.cssHooks.opacity={get:function(a,b){return Tc.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,
b){var c=a.style,e=a.currentStyle,f=d.isNumeric(b)?"alpha(opacity\x3d"+100*b+")":"",g=e&&e.filter||c.filter||"";c.zoom=1;if(1<=b&&""===d.trim(g.replace(Ma,""))&&(c.removeAttribute("filter"),e&&!e.filter))return;c.filter=Ma.test(g)?g.replace(Ma,f):g+" "+f}});d(function(){d.support.reliableMarginRight||(d.cssHooks.marginRight={get:function(a,b){var c;d.swap(a,{display:"inline-block"},function(){c=b?G(a,"margin-right","marginRight"):a.style.marginRight});return c}})});l.defaultView&&l.defaultView.getComputedStyle&&
(Lb=function(a,b){var c,e,f;b=b.replace(Uc,"-$1").toLowerCase();if((e=a.ownerDocument.defaultView)&&(f=e.getComputedStyle(a,null)))c=f.getPropertyValue(b),""===c&&!d.contains(a.ownerDocument.documentElement,a)&&(c=d.style(a,b));return c});l.documentElement.currentStyle&&(Mb=function(a,b){var c,d,f=a.currentStyle&&a.currentStyle[b],g=a.style;if(null===f&&g&&(c=g[b]))f=c;if(!Kb.test(f)&&Vc.test(f)){c=g.left;if(d=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;g.left="fontSize"===
b?"1em":f||0;f=g.pixelLeft+"px";g.left=c;d&&(a.runtimeStyle.left=d)}return""===f?"auto":f});G=Lb||Mb;d.expr&&d.expr.filters&&(d.expr.filters.hidden=function(a){var b=a.offsetHeight;return 0===a.offsetWidth&&0===b||!d.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||d.css(a,"display"))},d.expr.filters.visible=function(a){return!d.expr.filters.hidden(a)});var Yc=/%20/g,ac=/\[\]$/,Nb=/\r?\n/g,Zc=/#.*$/,$c=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,ad=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
bd=/^(?:GET|HEAD)$/,cd=/^\/\//,Ob=/\?/,dd=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,ed=/^(?:select|textarea)/i,$a=/\s+/,fd=/([?&])_=[^&]*/,Pb=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,Qb=d.fn.load,ua={},Rb={},D,F,Sb=["*/"]+["*"];try{D=cc.href}catch(od){D=l.createElement("a"),D.href="",D=D.href}F=Pb.exec(D.toLowerCase())||[];d.fn.extend({load:function(a,b,c){if("string"!==typeof a&&Qb)return Qb.apply(this,arguments);if(!this.length)return this;var e=a.indexOf(" ");if(0<=e){var f=
a.slice(e,a.length);a=a.slice(0,e)}e="GET";b&&(d.isFunction(b)?(c=b,b=void 0):"object"===typeof b&&(b=d.param(b,d.ajaxSettings.traditional),e="POST"));var g=this;d.ajax({url:a,type:e,dataType:"html",data:b,complete:function(a,b,e){e=a.responseText;a.isResolved()&&(a.done(function(a){e=a}),g.html(f?d("\x3cdiv\x3e").append(e.replace(dd,"")).find(f):e));c&&g.each(c,[e,b,a])}});return this},serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?
d.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||ed.test(this.nodeName)||ad.test(this.type))}).map(function(a,b){var c=d(this).val();return null==c?null:d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Nb,"\r\n")}}):{name:b.name,value:c.replace(Nb,"\r\n")}}).get()}});d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.each(["get","post"],
function(a,b){d[b]=function(a,e,f,g){d.isFunction(e)&&(g=g||f,f=e,e=void 0);return d.ajax({type:b,url:a,data:e,success:f,dataType:g})}});d.extend({getScript:function(a,b){return d.get(a,void 0,b,"script")},getJSON:function(a,b,c){return d.get(a,b,c,"json")},ajaxSetup:function(a,b){b?ab(a,d.ajaxSettings):(b=a,a=d.ajaxSettings);ab(a,b);return a},ajaxSettings:{url:D,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(F[1]),global:!0,type:"GET",contentType:"application/x-www-form-urlencoded",
processData:!0,async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":Sb},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":q.String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{context:!0,url:!0}},ajaxPrefilter:Za(ua),ajaxTransport:Za(Rb),ajax:function(a,b){function c(a,b,c,k){if(2!==u){u=2;q&&clearTimeout(q);p=void 0;m=k||
"";t.readyState=0<a?4:0;var l,o,r;k=b;if(c){var H=e,x=t,Aa=H.contents,v=H.dataTypes,ob=H.responseFields,A,z,w,I;for(z in ob)z in c&&(x[ob[z]]=c[z]);for(;"*"===v[0];)v.shift(),void 0===A&&(A=H.mimeType||x.getResponseHeader("content-type"));if(A)for(z in Aa)if(Aa[z]&&Aa[z].test(A)){v.unshift(z);break}if(v[0]in c)w=v[0];else{for(z in c){if(!v[0]||H.converters[z+" "+v[0]]){w=z;break}I||(I=z)}w=w||I}w?(w!==v[0]&&v.unshift(w),c=c[w]):c=void 0}else c=void 0;if(200<=a&&300>a||304===a){if(e.ifModified){if(A=
t.getResponseHeader("Last-Modified"))d.lastModified[n]=A;if(A=t.getResponseHeader("Etag"))d.etag[n]=A}if(304===a)k="notmodified",l=!0;else try{A=e;A.dataFilter&&(c=A.dataFilter(c,A.dataType));var J=A.dataTypes;z={};var D,F,L=J.length,G,N=J[0],B,K,O,P,C;for(D=1;D<L;D++){if(1===D)for(F in A.converters)"string"===typeof F&&(z[F.toLowerCase()]=A.converters[F]);B=N;N=J[D];if("*"===N)N=B;else if("*"!==B&&B!==N){K=B+" "+N;O=z[K]||z["* "+N];if(!O)for(P in C=void 0,z)if(G=P.split(" "),G[0]===B||"*"===G[0])if(C=
z[G[1]+" "+N]){P=z[P];!0===P?O=C:!0===C&&(O=P);break}!O&&!C&&d.error("No conversion from "+K.replace(" "," to "));!0!==O&&(c=O?O(c):C(P(c)))}}o=c;k="success";l=!0}catch(M){k="parsererror",r=M}}else if(r=k,!k||a)k="error",0>a&&(a=0);t.status=a;t.statusText=""+(b||k);l?h.resolveWith(f,[o,k,t]):h.rejectWith(f,[t,k,r]);t.statusCode(j);j=void 0;y&&g.trigger("ajax"+(l?"Success":"Error"),[t,e,l?o:r]);i.fireWith(f,[t,k]);y&&(g.trigger("ajaxComplete",[t,e]),--d.active||d.event.trigger("ajaxStop"))}}"object"===
typeof a&&(b=a,a=void 0);b=b||{};var e=d.ajaxSetup({},b),f=e.context||e,g=f!==e&&(f.nodeType||f instanceof d)?d(f):d.event,h=d.Deferred(),i=d.Callbacks("once memory"),j=e.statusCode||{},n,k={},l={},m,o,p,q,r,u=0,y,x,t={readyState:0,setRequestHeader:function(a,b){if(!u){var c=a.toLowerCase();a=l[c]=l[c]||a;k[a]=b}return this},getAllResponseHeaders:function(){return 2===u?m:null},getResponseHeader:function(a){var b;if(2===u){if(!o)for(o={};b=$c.exec(m);)o[b[1].toLowerCase()]=b[2];b=o[a.toLowerCase()]}return void 0===
b?null:b},overrideMimeType:function(a){u||(e.mimeType=a);return this},abort:function(a){a=a||"abort";p&&p.abort(a);c(0,a);return this}};h.promise(t);t.success=t.done;t.error=t.fail;t.complete=i.add;t.statusCode=function(a){if(a){var b;if(2>u)for(b in a)j[b]=[j[b],a[b]];else b=a[t.status],t.then(b,b)}return this};e.url=((a||e.url)+"").replace(Zc,"").replace(cd,F[1]+"//");e.dataTypes=d.trim(e.dataType||"*").toLowerCase().split($a);null==e.crossDomain&&(r=Pb.exec(e.url.toLowerCase()),e.crossDomain=!(!r||
!(r[1]!=F[1]||r[2]!=F[2]||(r[3]||("http:"===r[1]?80:443))!=(F[3]||("http:"===F[1]?80:443)))));e.data&&(e.processData&&"string"!==typeof e.data)&&(e.data=d.param(e.data,e.traditional));ba(ua,e,b,t);if(2===u)return!1;y=e.global;e.type=e.type.toUpperCase();e.hasContent=!bd.test(e.type);y&&0===d.active++&&d.event.trigger("ajaxStart");if(!e.hasContent&&(e.data&&(e.url+=(Ob.test(e.url)?"\x26":"?")+e.data,delete e.data),n=e.url,!1===e.cache)){r=d.now();var v=e.url.replace(fd,"$1_\x3d"+r);e.url=v+(v===e.url?
(Ob.test(e.url)?"\x26":"?")+"_\x3d"+r:"")}(e.data&&e.hasContent&&!1!==e.contentType||b.contentType)&&t.setRequestHeader("Content-Type",e.contentType);e.ifModified&&(n=n||e.url,d.lastModified[n]&&t.setRequestHeader("If-Modified-Since",d.lastModified[n]),d.etag[n]&&t.setRequestHeader("If-None-Match",d.etag[n]));t.setRequestHeader("Accept",e.dataTypes[0]&&e.accepts[e.dataTypes[0]]?e.accepts[e.dataTypes[0]]+("*"!==e.dataTypes[0]?", "+Sb+"; q\x3d0.01":""):e.accepts["*"]);for(x in e.headers)t.setRequestHeader(x,
e.headers[x]);if(e.beforeSend&&(!1===e.beforeSend.call(f,t,e)||2===u))return t.abort(),!1;for(x in{success:1,error:1,complete:1})t[x](e[x]);if(p=ba(Rb,e,b,t)){t.readyState=1;y&&g.trigger("ajaxSend",[t,e]);e.async&&0<e.timeout&&(q=setTimeout(function(){t.abort("timeout")},e.timeout));try{u=1,p.send(k,c)}catch(w){if(2>u)c(-1,w);else throw w;}}else c(-1,"No Transport");return t},param:function(a,b){var c=[],e=function(a,b){b=d.isFunction(b)?b():b;c[c.length]=encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)};
void 0===b&&(b=d.ajaxSettings.traditional);if(d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){e(this.name,this.value)});else for(var f in a)va(f,a[f],b,e);return c.join("\x26").replace(Yc,"+")}});d.extend({active:0,lastModified:{},etag:{}});var gd=d.now(),ra=/(\=)\?(&|$)|\?\?/i;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){return d.expando+"_"+gd++}});d.ajaxPrefilter("json jsonp",function(a,b,c){b="application/x-www-form-urlencoded"===a.contentType&&"string"===typeof a.data;
if("jsonp"===a.dataTypes[0]||!1!==a.jsonp&&(ra.test(a.url)||b&&ra.test(a.data))){var e,f=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,g=q[f],h=a.url,i=a.data,j="$1"+f+"$2";!1!==a.jsonp&&(h=h.replace(ra,j),a.url===h&&(b&&(i=i.replace(ra,j)),a.data===i&&(h+=(/\?/.test(h)?"\x26":"?")+a.jsonp+"\x3d"+f)));a.url=h;a.data=i;q[f]=function(a){e=[a]};c.always(function(){q[f]=g;if(e&&d.isFunction(g))q[f](e[0])});a.converters["script json"]=function(){e||d.error(f+" was not called");
return e[0]};a.dataTypes[0]="json";return"script"}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){d.globalEval(a);return a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c=l.head||l.getElementsByTagName("head")[0]||
l.documentElement;return{send:function(d,f){b=l.createElement("script");b.async="async";a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(a,d){if(d||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,c&&b.parentNode&&c.removeChild(b),b=void 0,d||f(200,"success")};c.insertBefore(b,c.firstChild)},abort:function(){if(b)b.onload(0,1)}}}});var Na=q.ActiveXObject?function(){for(var a in V)V[a](0,1)}:!1,hd=0,V;d.ajaxSettings.xhr=
q.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&bb()))a:{try{a=new q.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:bb;var Oa=d.ajaxSettings.xhr();d.extend(d.support,{ajax:!!Oa,cors:!!Oa&&"withCredentials"in Oa});d.support.ajax&&d.ajaxTransport(function(a){if(!a.crossDomain||d.support.cors){var b;return{send:function(c,e){var f=a.xhr(),g,h;a.username?f.open(a.type,a.url,a.async,a.username,a.password):f.open(a.type,a.url,a.async);if(a.xhrFields)for(h in a.xhrFields)f[h]=
a.xhrFields[h];a.mimeType&&f.overrideMimeType&&f.overrideMimeType(a.mimeType);!a.crossDomain&&!c["X-Requested-With"]&&(c["X-Requested-With"]="XMLHttpRequest");try{for(h in c)f.setRequestHeader(h,c[h])}catch(i){}f.send(a.hasContent&&a.data||null);b=function(c,h){var i,k,l,m,o;try{if(b&&(h||4===f.readyState))if(b=void 0,g&&(f.onreadystatechange=d.noop,Na&&delete V[g]),h)4!==f.readyState&&f.abort();else{i=f.status;l=f.getAllResponseHeaders();m={};if((o=f.responseXML)&&o.documentElement)m.xml=o;m.text=
f.responseText;try{k=f.statusText}catch(p){k=""}!i&&a.isLocal&&!a.crossDomain?i=m.text?200:404:1223===i&&(i=204)}}catch(q){h||e(-1,q)}m&&e(i,k,m,l)};!a.async||4===f.readyState?b():(g=++hd,Na&&(V||(V={},d(q).unload(Na)),V[g]=b),f.onreadystatechange=b)},abort:function(){b&&b(0,1)}}}});var wa={},v,K,id=/^(?:toggle|show|hide)$/,jd=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,sa,db=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],
["opacity"]],ca;d.fn.extend({show:function(a,b,c){if(a||0===a)return this.animate(B("show",3),a,b,c);c=0;for(var e=this.length;c<e;c++)a=this[c],a.style&&(b=a.style.display,!d._data(a,"olddisplay")&&"none"===b&&(b=a.style.display=""),""===b&&"none"===d.css(a,"display")&&d._data(a,"olddisplay",eb(a.nodeName)));for(c=0;c<e;c++)if(a=this[c],a.style&&(b=a.style.display,""===b||"none"===b))a.style.display=d._data(a,"olddisplay")||"";return this},hide:function(a,b,c){if(a||0===a)return this.animate(B("hide",
3),a,b,c);c=0;for(var e=this.length;c<e;c++)a=this[c],a.style&&(b=d.css(a,"display"),"none"!==b&&!d._data(a,"olddisplay")&&d._data(a,"olddisplay",b));for(c=0;c<e;c++)this[c].style&&(this[c].style.display="none");return this},_toggle:d.fn.toggle,toggle:function(a,b,c){var e="boolean"===typeof a;d.isFunction(a)&&d.isFunction(b)?this._toggle.apply(this,arguments):null==a||e?this.each(function(){var b=e?a:d(this).is(":hidden");d(this)[b?"show":"hide"]()}):this.animate(B("toggle",3),a,b,c);return this},
fadeTo:function(a,b,c,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){function f(){!1===g.queue&&d._mark(this);var b=d.extend({},g),c=1===this.nodeType,e=c&&d(this).is(":hidden"),f,k,l,m,o;b.animatedProperties={};for(l in a){f=d.camelCase(l);l!==f&&(a[f]=a[l],delete a[l]);k=a[f];d.isArray(k)?(b.animatedProperties[f]=k[1],k=a[f]=k[0]):b.animatedProperties[f]=b.specialEasing&&b.specialEasing[f]||b.easing||"swing";if("hide"===k&&e||
"show"===k&&!e)return b.complete.call(this);if(c&&("height"===f||"width"===f))b.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY],"inline"===d.css(this,"display")&&"none"===d.css(this,"float")&&(!d.support.inlineBlockNeedsLayout||"inline"===eb(this.nodeName)?this.style.display="inline-block":this.style.zoom=1)}null!=b.overflow&&(this.style.overflow="hidden");for(l in a)if(c=new d.fx(this,b,l),k=a[l],id.test(k))if(f=d._data(this,"toggle"+l)||("toggle"===k?e?"show":"hide":0))d._data(this,
"toggle"+l,"show"===f?"hide":"show"),c[f]();else c[k]();else f=jd.exec(k),m=c.cur(),f?(k=parseFloat(f[2]),o=f[3]||(d.cssNumber[l]?"":"px"),"px"!==o&&(d.style(this,l,(k||1)+o),m*=(k||1)/c.cur(),d.style(this,l,m+o)),f[1]&&(k=("-\x3d"===f[1]?-1:1)*k+m),c.custom(m,k,o)):c.custom(m,k,"");return!0}var g=d.speed(b,c,e);if(d.isEmptyObject(a))return this.each(g.complete,[!1]);a=d.extend({},a);return!1===g.queue?this.each(f):this.queue(g.queue,f)},stop:function(a,b,c){"string"!==typeof a&&(c=b,b=a,a=void 0);
b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b,f=!1,g=d.timers,h=d._data(this);c||d._unmark(!0,this);if(null==a)for(b in h){if(h[b]&&h[b].stop&&b.indexOf(".run")===b.length-4){var i=h[b];d.removeData(this,b,!0);i.stop(c)}}else if(h[b=a+".run"]&&h[b].stop)h=h[b],d.removeData(this,b,!0),h.stop(c);for(b=g.length;b--;)if(g[b].elem===this&&(null==a||g[b].queue===a)){if(c)g[b](!0);else g[b].saveState();f=!0;g.splice(b,1)}(!c||!f)&&d.dequeue(this,a)})}});d.each({slideDown:B("show",1),
slideUp:B("hide",1),slideToggle:B("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.extend({speed:function(a,b,c){var e=a&&"object"===typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};e.duration=d.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default;if(null==
e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(a){d.isFunction(e.old)&&e.old.call(this);e.queue?d.dequeue(this,e.queue):!1!==a&&d._unmark(this)};return e},easing:{linear:function(a,b,c,d){return c+d*a},swing:function(a,b,c,d){return(-Math.cos(a*Math.PI)/2+0.5)*d+c}},timers:[],fx:function(a,b,c){this.options=b;this.elem=a;this.prop=c;b.orig=b.orig||{}}});d.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(d.fx.step[this.prop]||
d.fx.step._default)(this)},cur:function(){if(null!=this.elem[this.prop]&&(!this.elem.style||null==this.elem.style[this.prop]))return this.elem[this.prop];var a,b=d.css(this.elem,this.prop);return isNaN(a=parseFloat(b))?!b||"auto"===b?0:b:a},custom:function(a,b,c){function e(a){return f.step(a)}var f=this,g=d.fx;this.startTime=ca||cb();this.end=b;this.now=this.start=a;this.pos=this.state=0;this.unit=c||this.unit||(d.cssNumber[this.prop]?"":"px");e.queue=this.options.queue;e.elem=this.elem;e.saveState=
function(){f.options.hide&&void 0===d._data(f.elem,"fxshow"+f.prop)&&d._data(f.elem,"fxshow"+f.prop,f.start)};e()&&(d.timers.push(e)&&!sa)&&(sa=setInterval(g.tick,g.interval))},show:function(){var a=d._data(this.elem,"fxshow"+this.prop);this.options.orig[this.prop]=a||d.style(this.elem,this.prop);this.options.show=!0;void 0!==a?this.custom(this.cur(),a):this.custom("width"===this.prop||"height"===this.prop?1:0,this.cur());d(this.elem).show()},hide:function(){this.options.orig[this.prop]=d._data(this.elem,
"fxshow"+this.prop)||d.style(this.elem,this.prop);this.options.hide=!0;this.custom(this.cur(),0)},step:function(a){var b,c=ca||cb(),e=!0,f=this.elem,g=this.options;if(a||c>=g.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();g.animatedProperties[this.prop]=!0;for(b in g.animatedProperties)!0!==g.animatedProperties[b]&&(e=!1);if(e){null!=g.overflow&&!d.support.shrinkWrapBlocks&&d.each(["","X","Y"],function(a,b){f.style["overflow"+b]=g.overflow[a]});g.hide&&d(f).hide();
if(g.hide||g.show)for(b in g.animatedProperties)d.style(f,b,g.orig[b]),d.removeData(f,"fxshow"+b,!0),d.removeData(f,"toggle"+b,!0);if(a=g.complete)g.complete=!1,a.call(f)}return!1}Infinity==g.duration?this.now=c:(a=c-this.startTime,this.state=a/g.duration,this.pos=d.easing[g.animatedProperties[this.prop]](this.state,a,0,1,g.duration),this.now=this.start+(this.end-this.start)*this.pos);this.update();return!0}};d.extend(d.fx,{tick:function(){for(var a,b=d.timers,c=0;c<b.length;c++)a=b[c],!a()&&b[c]===
a&&b.splice(c--,1);b.length||d.fx.stop()},interval:13,stop:function(){clearInterval(sa);sa=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){d.style(a.elem,"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}}});d.each(["width","height"],function(a,b){d.fx.step[b]=function(a){d.style(a.elem,b,Math.max(0,a.now)+a.unit)}});d.expr&&d.expr.filters&&(d.expr.filters.animated=function(a){return d.grep(d.timers,
function(b){return a===b.elem}).length});var kd=/^t(?:able|d|h)$/i,Tb=/^(?:body|html)$/i;d.fn.offset="getBoundingClientRect"in l.documentElement?function(a){var b=this[0],c;if(a)return this.each(function(b){d.offset.setOffset(this,a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return d.offset.bodyOffset(b);try{c=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,g=f.documentElement;if(!c||!d.contains(g,b))return c?{top:c.top,left:c.left}:{top:0,left:0};b=f.body;f=xa(f);
return{top:c.top+(f.pageYOffset||d.support.boxModel&&g.scrollTop||b.scrollTop)-(g.clientTop||b.clientTop||0),left:c.left+(f.pageXOffset||d.support.boxModel&&g.scrollLeft||b.scrollLeft)-(g.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(b){d.offset.setOffset(this,a,b)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return d.offset.bodyOffset(b);var c,e=b.offsetParent,f=b.ownerDocument,g=f.documentElement,h=f.body;c=(f=f.defaultView)?f.getComputedStyle(b,
null):b.currentStyle;for(var i=b.offsetTop,j=b.offsetLeft;(b=b.parentNode)&&(b!==h&&b!==g)&&!(d.support.fixedPosition&&"fixed"===c.position);){c=f?f.getComputedStyle(b,null):b.currentStyle;i-=b.scrollTop;j-=b.scrollLeft;if(b===e){i+=b.offsetTop;j+=b.offsetLeft;if(d.support.doesNotAddBorder&&(!d.support.doesAddBorderForTableAndCells||!kd.test(b.nodeName)))i+=parseFloat(c.borderTopWidth)||0,j+=parseFloat(c.borderLeftWidth)||0;e=b.offsetParent}d.support.subtractsBorderForOverflowNotVisible&&"visible"!==
c.overflow&&(i+=parseFloat(c.borderTopWidth)||0,j+=parseFloat(c.borderLeftWidth)||0)}if("relative"===c.position||"static"===c.position)i+=h.offsetTop,j+=h.offsetLeft;d.support.fixedPosition&&"fixed"===c.position&&(i+=Math.max(g.scrollTop,h.scrollTop),j+=Math.max(g.scrollLeft,h.scrollLeft));return{top:i,left:j}};d.offset={bodyOffset:function(a){var b=a.offsetTop,c=a.offsetLeft;d.support.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(d.css(a,"marginTop"))||0,c+=parseFloat(d.css(a,"marginLeft"))||
0);return{top:b,left:c}},setOffset:function(a,b,c){var e=d.css(a,"position");"static"===e&&(a.style.position="relative");var f=d(a),g=f.offset(),h=d.css(a,"top"),i=d.css(a,"left"),j={},k={};("absolute"===e||"fixed"===e)&&-1<d.inArray("auto",[h,i])?(k=f.position(),e=k.top,i=k.left):(e=parseFloat(h)||0,i=parseFloat(i)||0);d.isFunction(b)&&(b=b.call(a,c,g));null!=b.top&&(j.top=b.top-g.top+e);null!=b.left&&(j.left=b.left-g.left+i);"using"in b?b.using.call(a,j):f.css(j)}};d.fn.extend({position:function(){if(!this[0])return null;
var a=this[0],b=this.offsetParent(),c=this.offset(),e=Tb.test(b[0].nodeName)?{top:0,left:0}:b.offset();c.top-=parseFloat(d.css(a,"marginTop"))||0;c.left-=parseFloat(d.css(a,"marginLeft"))||0;e.top+=parseFloat(d.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(d.css(b[0],"borderLeftWidth"))||0;return{top:c.top-e.top,left:c.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||l.body;a&&!Tb.test(a.nodeName)&&"static"===d.css(a,"position");)a=a.offsetParent;return a})}});
d.each(["Left","Top"],function(a,b){var c="scroll"+b;d.fn[c]=function(b){var f,g;return void 0===b?(f=this[0],!f?null:(g=xa(f))?"pageXOffset"in g?g[a?"pageYOffset":"pageXOffset"]:d.support.boxModel&&g.document.documentElement[c]||g.document.body[c]:f[c]):this.each(function(){(g=xa(this))?g.scrollTo(!a?b:d(g).scrollLeft(),a?b:d(g).scrollTop()):this[c]=b})}});d.each(["Height","Width"],function(a,b){var c=b.toLowerCase();d.fn["inner"+b]=function(){var a=this[0];return a?a.style?parseFloat(d.css(a,c,
"padding")):this[c]():null};d.fn["outer"+b]=function(a){var b=this[0];return b?b.style?parseFloat(d.css(b,c,a?"margin":"border")):this[c]():null};d.fn[c]=function(a){var f=this[0];if(!f)return null==a?null:this;if(d.isFunction(a))return this.each(function(b){var f=d(this);f[c](a.call(this,b,f[c]()))});if(d.isWindow(f)){var g=f.document.documentElement["client"+b],h=f.document.body;return"CSS1Compat"===f.document.compatMode&&g||h&&h["client"+b]||g}return 9===f.nodeType?Math.max(f.documentElement["client"+
b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]):void 0===a?(f=d.css(f,c),g=parseFloat(f),d.isNumeric(g)?g:f):this.css(c,"string"===typeof a?a:a+"px")}});q.jQuery=q.$=d;"function"===typeof define&&(define.amd&&define.amd.jQuery)&&define("jquery",[],function(){return d})})(window);