// Copyright 2013, Matthew Cobbs

// Licensed under the MIT license.

define("jquery wrap/modernizr util/util util/stitches util/templates modules/file-manager modules/drop-box modules/canvas modules/toolbar modules/palette".split(" "),function(d,e,g,h,i,j,k,l,m,f){("undefined"===typeof FileReader||!e.draganddrop)&&require(["../lib/dropfile/dropfile"]);e.canvas||require(["../lib/flashcanvas/flashcanvas"]);var n={layout:"compact",prefix:"sprite",padding:5,uri:!1};e=function(a,b){this.$element=d(a);this.settings=d.extend({},n,b);this.init()};e.prototype={constructor:e,
init:function(){this.render();this.proxy();this.bind();this.setFileManager();this.setDropBox();this.setToolbar();this.setLayout();this.setCanvas();this.setPalettes()},render:function(){var a=i.stitches({});this.$element.append(a);this.$overlay=this.$element.find(".stitches-overlay");this.$dropBox=this.$element.find(".stitches-drop-box");this.$toolbar=this.$element.find(".stitches-toolbar");this.$canvas=this.$element.find(".stitches-canvas");this.$progress=this.$element.find(".stitches-progress .progress");
this.$progressBar=this.$element.find(".stitches-progress .bar");this.$about=this.$element.find(".stitches-about");this.$settings=this.$element.find(".stitches-settings");this.$properties=this.$element.find(".stitches-properties")},proxy:function(){g.proxy(this,"showOverlay hideOverlay openAbout closeAbout openSettings closeSettings openProperties closeProperties closePalettes processFiles updateToolbar updateProgress errorHandler")},bind:function(){this.$element.on("show-overlay",this.showOverlay);
this.$element.on("hide-overlay",this.hideOverlay);this.$element.on("open-about",this.openAbout);this.$element.on("close-about",this.closeAbout);this.$element.on("open-settings",this.openSettings);this.$element.on("close-settings",this.closeSettings);this.$element.on("open-properties",this.openProperties);this.$element.on("close-properties",this.closeProperties);this.$element.on("close-palettes",this.closePalettes);this.$element.on("process-files",this.processFiles);this.$element.on("update-toolbar",
this.updateToolbar);this.$element.on("error",this.errorHandler)},setFileManager:function(){this.fileManager=new j(this.$canvas,{progress:this.updateProgress})},setDropBox:function(){this.dropBox=new k(this.$dropBox)},setLayout:function(){h.setLayout(this.settings.layout)},setCanvas:function(){this.canvas=new l(this.$canvas,{padding:this.settings.padding,progress:this.updateProgress})},setToolbar:function(){var a=this;this.toolbar=new m(this.$toolbar,{name:"toolbar",actions:{open:{change:function(b){var c=
a.$toolbar.find("input[type\x3dfile]"),d=c.clone(!0).val("");a.$element.trigger("process-files",[b.target.files]);c.replaceWith(d)}},settings:{click:function(){a.$element.trigger("open-settings")}},reset:{click:function(){a.canvas.reset()}},generate:{click:function(){a.$element.trigger("show-overlay");a.canvas.generateSheets(a.settings);a.$element.trigger("hide-overlay")}},clear:{click:function(){a.canvas.clear()}},spritesheet:{click:function(){}},stylesheet:{click:function(){}},about:{click:function(){a.$element.trigger("open-about")}}}})},
setPalettes:function(){var a=this,b=new f(this.$about,{name:"about",visible:!0,actions:{close:{click:function(){this.close()}}}}),c=new f(this.$settings,{name:"settings",visible:!1,actions:{close:{click:function(){a.$element.trigger("close-settings")}}},fields:{layout:{change:function(){var b=this.$element.find("input[name\x3dlayout]:checked").val();this.source.layout=b;h.setLayout(b);a.canvas.reset()}},prefix:{"input blur":function(a){a=d(a.currentTarget).val();this.source.prefix=a}},padding:{"input blur":function(b){var c=
d(b.currentTarget).val();this.source.padding=c;a.canvas.padding=c;d.map(a.canvas.sprites,function(a){a.configure({padding:c})});a.canvas.reset()}},uri:{change:function(a){a=d(a.currentTarget).is(":checked");this.source.uri=a}}}}),e=new f(this.$properties,{name:"properties",visible:!1,actions:{close:{click:function(){a.$element.trigger("close-properties")}},remove:{click:function(){a.canvas.remove(this.source)}}},fields:{name:{"input blur":function(a){var b=d(a.currentTarget).val(),c=g.cleanName(b);
this.source.name=c;b!==c&&d(a.currentTarget).val(c)}}}});this.palettes={about:b,settings:c,properties:e}},showOverlay:function(){this.$overlay.fadeTo("fast",0.4)},hideOverlay:function(){this.$overlay.fadeOut("fast")},openAbout:function(){this.closePalettes();this.palettes.about.open()},closeAbout:function(){this.palettes.about.visible&&this.palettes.about.close()},openSettings:function(){this.closePalettes();this.palettes.settings.configure({source:this.settings,inputs:{layout:this.settings.layout,
prefix:this.settings.prefix,padding:this.settings.padding,uri:this.settings.uri}});this.palettes.settings.open()},closeSettings:function(){this.palettes.settings.visible&&this.palettes.settings.close()},openProperties:function(a,b){this.closePalettes();this.palettes.properties.configure({source:b,inputs:{name:b.name,x:b.x+b.padding,y:b.y+b.padding}});this.palettes.properties.open()},closeProperties:function(){this.palettes.properties.visible&&(this.palettes.properties.close(),this.canvas.$element.trigger("clear-active",
[!0]))},closePalettes:function(){this.closeAbout();this.closeSettings();this.closeProperties()},processFiles:function(a,b){this.fileManager.processFiles(b)},updateToolbar:function(){var a=this.toolbar.$element,b=this.toolbar,c=this.canvas;c.sprites.length?b.enable("reset generate clear"):b.disable("reset generate clear");c.spritesheet&&c.stylesheet?(a.find("[data-action\x3dspritesheet]").attr("href",c.spritesheet),a.find("[data-action\x3dstylesheet]").attr("href",c.stylesheet),b.enable("spritesheet stylesheet")):
(a.find("[data-action\x3dspritesheet]").attr("href","#"),a.find("[data-action\x3dstylesheet]").attr("href","#"),b.disable("spritesheet stylesheet"))},updateProgress:function(a,b){var c=Math.ceil(100*a);100===c&&("danger"!==b&&"warning"!==b)&&(b="success");b&&this.$progress.attr({"class":"progress progress-striped progress-"+b});this.$progressBar.css({width:c+"%"})},errorHandler:function(a,b,c){this.updateProgress(1,c||"warning")}};return e});