/** vim: et:ts=4:sw=4:sts=4
 * @license RequireJS 2.1.4 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 * Available via the MIT or new BSD license.
 * see: http://github.com/jrburke/requirejs for details
 */

/*
 RequireJS 2.1.4 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
var requirejs,require,define;
(function(X){function H(b){return"[object Function]"===K.call(b)}function I(b){return"[object Array]"===K.call(b)}function w(b,c){if(b){var d;for(d=0;d<b.length&&(!b[d]||!c(b[d],d,b));d+=1);}}function L(b,c){if(b){var d;for(d=b.length-1;-1<d&&(!b[d]||!c(b[d],d,b));d-=1);}}function q(b,c){return ca.call(b,c)}function i(b,c){return q(b,c)&&b[c]}function D(b,c){for(var d in b)if(q(b,d)&&c(b[d],d))break}function P(b,c,d,i){c&&D(c,function(c,h){if(d||!q(b,h))i&&"string"!==typeof c?(b[h]||(b[h]={}),P(b[h],
c,d,i)):b[h]=c});return b}function s(b,c){return function(){return c.apply(b,arguments)}}function Y(b){if(!b)return b;var c=X;w(b.split("."),function(b){c=c[b]});return c}function E(b,c,d,i){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=i;d&&(c.originalError=d);return c}function da(b){function c(a,f,u){var e,n,b,c,d,k,g,h=f&&f.split("/");e=h;var l=m.map,j=l&&l["*"];if(a&&"."===a.charAt(0))if(f){e=i(m.pkgs,f)?h=[f]:h.slice(0,h.length-1);f=a=e.concat(a.split("/"));
for(e=0;f[e];e+=1)if(n=f[e],"."===n)f.splice(e,1),e-=1;else if(".."===n)if(1===e&&(".."===f[2]||".."===f[0]))break;else 0<e&&(f.splice(e-1,2),e-=2);e=i(m.pkgs,f=a[0]);a=a.join("/");e&&a===f+"/"+e.main&&(a=f)}else 0===a.indexOf("./")&&(a=a.substring(2));if(u&&(h||j)&&l){f=a.split("/");for(e=f.length;0<e;e-=1){b=f.slice(0,e).join("/");if(h)for(n=h.length;0<n;n-=1)if(u=i(l,h.slice(0,n).join("/")))if(u=i(u,b)){c=u;d=e;break}if(c)break;!k&&(j&&i(j,b))&&(k=i(j,b),g=e)}!c&&k&&(c=k,d=g);c&&(f.splice(0,d,
c),a=f.join("/"))}return a}function d(a){y&&w(document.getElementsByTagName("script"),function(f){if(f.getAttribute("data-requiremodule")===a&&f.getAttribute("data-requirecontext")===k.contextName)return f.parentNode.removeChild(f),!0})}function x(a){var f=i(m.paths,a);if(f&&I(f)&&1<f.length)return d(a),f.shift(),k.require.undef(a),k.require([a]),!0}function g(a){var f,b=a?a.indexOf("!"):-1;-1<b&&(f=a.substring(0,b),a=a.substring(b+1,a.length));return[f,a]}function h(a,f,b,e){var n,t,d=null,h=f?f.name:
null,l=a,m=!0,j="";a||(m=!1,a="_@r"+(K+=1));a=g(a);d=a[0];a=a[1];d&&(d=c(d,h,e),t=i(o,d));a&&(d?j=t&&t.normalize?t.normalize(a,function(a){return c(a,h,e)}):c(a,h,e):(j=c(a,h,e),a=g(j),d=a[0],j=a[1],b=!0,n=k.nameToUrl(j)));b=d&&!t&&!b?"_unnormalized"+(L+=1):"";return{prefix:d,name:j,parentMap:f,unnormalized:!!b,url:n,originalName:l,isDefine:m,id:(d?d+"!"+j:j)+b}}function p(a){var f=a.id,b=i(j,f);b||(b=j[f]=new k.Module(a));return b}function r(a,f,b){var e=a.id,n=i(j,e);if(q(o,e)&&(!n||n.defineEmitComplete))"defined"===
f&&b(o[e]);else p(a).on(f,b)}function z(a,f){var b=a.requireModules,e=!1;if(f)f(a);else if(w(b,function(f){if(f=i(j,f))f.error=a,f.events.error&&(e=!0,f.emit("error",a))}),!e)l.onError(a)}function v(){Q.length&&(ea.apply(F,[F.length-1,0].concat(Q)),Q=[])}function A(a,f,b){var e=a.map.id;a.error?a.emit("error",a.error):(f[e]=!0,w(a.depMaps,function(e,c){var d=e.id,h=i(j,d);h&&(!a.depMatched[c]&&!b[d])&&(i(f,d)?(a.defineDep(c,o[d]),a.check()):A(h,f,b))}),b[e]=!0)}function B(){var a,f,b,e,n=(b=1E3*m.waitSeconds)&&
k.startTime+b<(new Date).getTime(),c=[],h=[],g=!1,l=!0;if(!S){S=!0;D(j,function(b){a=b.map;f=a.id;if(b.enabled&&(a.isDefine||h.push(b),!b.error))if(!b.inited&&n)x(f)?g=e=!0:(c.push(f),d(f));else if(!b.inited&&(b.fetched&&a.isDefine)&&(g=!0,!a.prefix))return l=!1});if(n&&c.length)return b=E("timeout","Load timeout for modules: "+c,null,c),b.contextName=k.contextName,z(b);l&&w(h,function(a){A(a,{},{})});if((!n||e)&&g)if((y||Z)&&!T)T=setTimeout(function(){T=0;B()},50);S=!1}}function C(a){q(o,a[0])||
p(h(a[0],null,!0)).init(a[1],a[2])}function G(a){a=a.currentTarget||a.srcElement;var b=k.onScriptLoad;a.detachEvent&&!U?a.detachEvent("onreadystatechange",b):a.removeEventListener("load",b,!1);b=k.onScriptError;(!a.detachEvent||U)&&a.removeEventListener("error",b,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}function J(){var a;for(v();F.length;){a=F.shift();if(null===a[0])return z(E("mismatch","Mismatched anonymous define() module: "+a[a.length-1]));C(a)}}var S,V,k,M,T,m={waitSeconds:7,
baseUrl:"./",paths:{},pkgs:{},shim:{},map:{},config:{}},j={},W={},F=[],o={},R={},K=1,L=1;M={require:function(a){return a.require?a.require:a.require=k.makeRequire(a.map)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports?a.exports:a.exports=o[a.map.id]={}},module:function(a){return a.module?a.module:a.module={id:a.map.id,uri:a.map.url,config:function(){return m.config&&i(m.config,a.map.id)||{}},exports:o[a.map.id]}}};V=function(a){this.events=i(W,a.id)||{};this.map=a;this.shim=
i(m.shim,a.id);this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};V.prototype={init:function(a,b,c,e){e=e||{};if(!this.inited){this.factory=b;if(c)this.on("error",c);else this.events.error&&(c=s(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.errback=c;this.inited=!0;this.ignore=e.ignore;e.enabled||this.enabled?this.enable():this.check()}},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,this.depCount-=1,this.depExports[a]=
b)},fetch:function(){if(!this.fetched){this.fetched=!0;k.startTime=(new Date).getTime();var a=this.map;if(this.shim)k.makeRequire(this.map,{enableBuildCallback:!0})(this.shim.deps||[],s(this,function(){return a.prefix?this.callPlugin():this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=this.map.url;R[a]||(R[a]=!0,k.load(this.map.id,a))},check:function(){if(this.enabled&&!this.enabling){var a,b,c=this.map.id;b=this.depExports;var e=this.exports,n=this.factory;
if(this.inited)if(this.error)this.emit("error",this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(H(n)){if(this.events.error)try{e=k.execCb(c,n,b,e)}catch(d){a=d}else e=k.execCb(c,n,b,e);this.map.isDefine&&((b=this.module)&&void 0!==b.exports&&b.exports!==this.exports?e=b.exports:void 0===e&&this.usingExports&&(e=this.exports));if(a)return a.requireMap=this.map,a.requireModules=[this.map.id],a.requireType="define",z(this.error=a)}else e=n;this.exports=e;if(this.map.isDefine&&
!this.ignore&&(o[c]=e,l.onResourceLoad))l.onResourceLoad(k,this.map,this.depMaps);delete j[c];this.defined=!0}this.defining=!1;this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}else this.fetch()}},callPlugin:function(){var a=this.map,b=a.id,d=h(a.prefix);this.depMaps.push(d);r(d,"defined",s(this,function(e){var n,d;d=this.map.name;var u=this.map.parentMap?this.map.parentMap.name:null,g=k.makeRequire(a.parentMap,{enableBuildCallback:!0});
if(this.map.unnormalized){if(e.normalize&&(d=e.normalize(d,function(a){return c(a,u,!0)})||""),e=h(a.prefix+"!"+d,this.map.parentMap),r(e,"defined",s(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),d=i(j,e.id)){this.depMaps.push(e);if(this.events.error)d.on("error",s(this,function(a){this.emit("error",a)}));d.enable()}}else n=s(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),n.error=s(this,function(a){this.inited=!0;this.error=a;a.requireModules=
[b];D(j,function(a){0===a.map.id.indexOf(b+"_unnormalized")&&delete j[a.map.id]});z(a)}),n.fromText=s(this,function(e,c){var d=a.name,t=h(d),u=N;c&&(e=c);u&&(N=!1);p(t);q(m.config,b)&&(m.config[d]=m.config[b]);try{l.exec(e)}catch(j){return z(E("fromtexteval","fromText eval for "+b+" failed: "+j,j,[b]))}u&&(N=!0);this.depMaps.push(t);k.completeLoad(d);g([d],n)}),e.load(a.name,g,n,m)}));k.enable(d,this);this.pluginMaps[d.id]=d},enable:function(){this.enabling=this.enabled=!0;w(this.depMaps,s(this,function(a,
b){var c,e;if("string"===typeof a){a=h(a,this.map.isDefine?this.map:this.map.parentMap,!1,!this.skipMap);this.depMaps[b]=a;if(c=i(M,a.id)){this.depExports[b]=c(this);return}this.depCount+=1;r(a,"defined",s(this,function(a){this.defineDep(b,a);this.check()}));this.errback&&r(a,"error",this.errback)}c=a.id;e=j[c];!q(M,c)&&(e&&!e.enabled)&&k.enable(a,this)}));D(this.pluginMaps,s(this,function(a){var b=i(j,a.id);b&&!b.enabled&&k.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var c=
this.events[a];c||(c=this.events[a]=[]);c.push(b)},emit:function(a,b){w(this.events[a],function(a){a(b)});"error"===a&&delete this.events[a]}};k={config:m,contextName:b,registry:j,defined:o,urlFetched:R,defQueue:F,Module:V,makeModuleMap:h,nextTick:l.nextTick,configure:function(a){a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var b=m.pkgs,c=m.shim,e={paths:!0,config:!0,map:!0};D(a,function(a,b){e[b]?"map"===b?P(m[b],a,!0,!0):P(m[b],a,!0):m[b]=a});a.shim&&(D(a.shim,function(a,
b){I(a)&&(a={deps:a});if((a.exports||a.init)&&!a.exportsFn)a.exportsFn=k.makeShimExports(a);c[b]=a}),m.shim=c);a.packages&&(w(a.packages,function(a){a="string"===typeof a?{name:a}:a;b[a.name]={name:a.name,location:a.location||a.name,main:(a.main||"main").replace(fa,"").replace($,"")}}),m.pkgs=b);D(j,function(a,b){!a.inited&&!a.map.unnormalized&&(a.map=h(b))});if(a.deps||a.callback)k.require(a.deps||[],a.callback)},makeShimExports:function(a){return function(){var b;a.init&&(b=a.init.apply(X,arguments));
return b||a.exports&&Y(a.exports)}},makeRequire:function(a,d){function g(e,c,t){var i,m;d.enableBuildCallback&&(c&&H(c))&&(c.__requireJsBuild=!0);if("string"===typeof e){if(H(c))return z(E("requireargs","Invalid require call"),t);if(a&&q(M,e))return M[e](j[a.id]);if(l.get)return l.get(k,e,a);i=h(e,a,!1,!0);i=i.id;return!q(o,i)?z(E("notloaded",'Module name "'+i+'" has not been loaded yet for context: '+b+(a?"":". Use require([])"))):o[i]}J();k.nextTick(function(){J();m=p(h(null,a));m.skipMap=d.skipMap;
m.init(e,c,t,{enabled:!0});B()});return g}d=d||{};P(g,{isBrowser:y,toUrl:function(b){var d,f=b.lastIndexOf("."),h=b.split("/")[0];if(-1!==f&&(!("."===h||".."===h)||1<f))d=b.substring(f,b.length),b=b.substring(0,f);b=k.nameToUrl(c(b,a&&a.id,!0),d||".fake");return d?b:b.substring(0,b.length-5)},defined:function(b){return q(o,h(b,a,!1,!0).id)},specified:function(b){b=h(b,a,!1,!0).id;return q(o,b)||q(j,b)}});a||(g.undef=function(b){v();var c=h(b,a,!0),d=i(j,b);delete o[b];delete R[c.url];delete W[b];
d&&(d.events.defined&&(W[b]=d.events),delete j[b])});return g},enable:function(a){i(j,a.id)&&p(a).enable()},completeLoad:function(a){var b,c,d=i(m.shim,a)||{},h=d.exports;for(v();F.length;){c=F.shift();if(null===c[0]){c[0]=a;if(b)break;b=!0}else c[0]===a&&(b=!0);C(c)}c=i(j,a);if(!b&&!q(o,a)&&c&&!c.inited){if(m.enforceDefine&&(!h||!Y(h)))return x(a)?void 0:z(E("nodefine","No define call for "+a,null,[a]));C([a,d.deps||[],d.exportsFn])}B()},nameToUrl:function(a,b){var c,d,h,g,k,j;if(l.jsExtRegExp.test(a))g=
a+(b||"");else{c=m.paths;d=m.pkgs;g=a.split("/");for(k=g.length;0<k;k-=1)if(j=g.slice(0,k).join("/"),h=i(d,j),j=i(c,j)){I(j)&&(j=j[0]);g.splice(0,k,j);break}else if(h){c=a===h.name?h.location+"/"+h.main:h.location;g.splice(0,k,c);break}g=g.join("/");g+=b||(/\?/.test(g)?"":".js");g=("/"===g.charAt(0)||g.match(/^[\w\+\.\-]+:/)?"":m.baseUrl)+g}return m.urlArgs?g+((-1===g.indexOf("?")?"?":"\x26")+m.urlArgs):g},load:function(a,b){l.load(k,a,b)},execCb:function(a,b,c,d){return b.apply(d,c)},onScriptLoad:function(a){if("load"===
a.type||ga.test((a.currentTarget||a.srcElement).readyState))O=null,a=G(a),k.completeLoad(a.id)},onScriptError:function(a){var b=G(a);if(!x(b.id))return z(E("scripterror","Script error",a,[b.id]))}};k.require=k.makeRequire();return k}var l,v,A,C,r,G,O,J,aa,ba,ha=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,ia=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,$=/\.js$/,fa=/^\.\//;v=Object.prototype;var K=v.toString,ca=v.hasOwnProperty,ea=Array.prototype.splice,y=!!("undefined"!==typeof window&&navigator&&
document),Z=!y&&"undefined"!==typeof importScripts,ga=y&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,U="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),B={},p={},Q=[],N=!1;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(H(requirejs))return;p=requirejs;requirejs=void 0}"undefined"!==typeof require&&!H(require)&&(p=require,require=void 0);l=requirejs=function(b,c,d,x){var g,h="_";!I(b)&&"string"!==typeof b&&(g=b,I(c)?(b=c,c=d,d=x):b=[]);
g&&g.context&&(h=g.context);(x=i(B,h))||(x=B[h]=l.s.newContext(h));g&&x.configure(g);return x.require(b,c,d)};l.config=function(b){return l(b)};l.nextTick="undefined"!==typeof setTimeout?function(b){setTimeout(b,4)}:function(b){b()};require||(require=l);l.version="2.1.4";l.jsExtRegExp=/^\/|:|\?|\.js$/;l.isBrowser=y;v=l.s={contexts:B,newContext:da};l({});w(["toUrl","undef","defined","specified"],function(b){l[b]=function(){var c=B._;return c.require[b].apply(c,arguments)}});if(y&&(A=v.head=document.getElementsByTagName("head")[0],
C=document.getElementsByTagName("base")[0]))A=v.head=C.parentNode;l.onError=function(b){throw b;};l.load=function(b,c,d){var i=b&&b.config||{},g;if(y)return g=i.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script"),g.type=i.scriptType||"text/javascript",g.charset="utf-8",g.async=!0,g.setAttribute("data-requirecontext",b.contextName),g.setAttribute("data-requiremodule",c),g.attachEvent&&!(g.attachEvent.toString&&0>g.attachEvent.toString().indexOf("[native code"))&&
!U?(N=!0,g.attachEvent("onreadystatechange",b.onScriptLoad)):(g.addEventListener("load",b.onScriptLoad,!1),g.addEventListener("error",b.onScriptError,!1)),g.src=d,J=g,C?A.insertBefore(g,C):A.appendChild(g),J=null,g;Z&&(importScripts(d),b.completeLoad(c))};y&&L(document.getElementsByTagName("script"),function(b){A||(A=b.parentNode);if(r=b.getAttribute("data-main"))return p.baseUrl||(G=r.split("/"),aa=G.pop(),ba=G.length?G.join("/")+"/":"./",p.baseUrl=ba,r=aa),r=r.replace($,""),p.deps=p.deps?p.deps.concat(r):
[r],!0});define=function(b,c,d){var i,g;"string"!==typeof b&&(d=c,c=b,b=null);I(c)||(d=c,c=[]);!c.length&&H(d)&&d.length&&(d.toString().replace(ha,"").replace(ia,function(b,d){c.push(d)}),c=(1===d.length?["require"]:["require","exports","module"]).concat(c));if(N){if(!(i=J))O&&"interactive"===O.readyState||L(document.getElementsByTagName("script"),function(b){if("interactive"===b.readyState)return O=b}),i=O;i&&(b||(b=i.getAttribute("data-requiremodule")),g=B[i.getAttribute("data-requirecontext")])}(g?
g.defQueue:Q).push([b,c,d])};define.amd={jQuery:!0};l.exec=function(b){return eval(b)};l(p)}})(this);