/**
 * @license RequireJS text 2.0.5+ Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 * Available via the MIT or new BSD license.
 * see: http://github.com/requirejs/text for details
 */

/*
 RequireJS text 2.0.5+ Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/text for details
*/
define(["module"],function(n){var f,o,l,i,p=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],q=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,r=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,j="undefined"!==typeof location&&location.href,s=j&&location.protocol&&location.protocol.replace(/\:/,""),t=j&&location.hostname,u=j&&(location.port||void 0),m=[],g=n.config&&n.config()||{};f={version:"2.0.5+",strip:function(a){if(a){a=a.replace(q,"");var e=a.match(r);e&&(a=e[1])}else a="";return a},
jsEscape:function(a){return a.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r").replace(/[\u2028]/g,"\\u2028").replace(/[\u2029]/g,"\\u2029")},createXhr:g.createXhr||function(){var a,e,c;if("undefined"!==typeof XMLHttpRequest)return new XMLHttpRequest;if("undefined"!==typeof ActiveXObject)for(e=0;3>e;e+=1){c=p[e];try{a=new ActiveXObject(c)}catch(d){}if(a){p=[c];break}}return a},parseName:function(a){var e,
c,d=!1,b=a.indexOf(".");e=0===a.indexOf("./")||0===a.indexOf("../");-1!==b&&(!e||1<b)?(e=a.substring(0,b),c=a.substring(b+1,a.length)):e=a;a=c||e;b=a.indexOf("!");-1!==b&&(d="strip"===a.substring(b+1),a=a.substring(0,b),c?c=a:e=a);return{moduleName:e,ext:c,strip:d}},xdRegExp:/^((\w+)\:)?\/\/([^\/\\]+)/,useXhr:function(a,e,c,d){var b,h;b=f.xdRegExp.exec(a);if(!b)return!0;a=b[2];b=b[3];b=b.split(":");h=b[1];b=b[0];return(!a||a===e)&&(!b||b.toLowerCase()===c.toLowerCase())&&(!h&&!b||h===d)},finishLoad:function(a,
e,c,d){c=e?f.strip(c):c;g.isBuild&&(m[a]=c);d(c)},load:function(a,e,c,d){if(d.isBuild&&!d.inlineText)c();else{g.isBuild=d.isBuild;var b=f.parseName(a);d=b.moduleName+(b.ext?"."+b.ext:"");var h=e.toUrl(d),k=g.useXhr||f.useXhr;!j||k(h,s,t,u)?f.get(h,function(e){f.finishLoad(a,b.strip,e,c)},function(a){c.error&&c.error(a)}):e([d],function(a){f.finishLoad(b.moduleName+"."+b.ext,b.strip,a,c)})}},write:function(a,e,c){if(m.hasOwnProperty(e)){var d=f.jsEscape(m[e]);c.asModule(a+"!"+e,"define(function () { return '"+
d+"';});\n")}},writeFile:function(a,e,c,d,b){e=f.parseName(e);var h=e.ext?"."+e.ext:"",k=e.moduleName+h,g=c.toUrl(e.moduleName+h)+".js";f.load(k,c,function(){var c=function(a){return d(g,a)};c.asModule=function(a,b){return d.asModule(a,g,b)};f.write(a,k,c,b)},b)}};if("node"===g.env||!g.env&&"undefined"!==typeof process&&process.versions&&process.versions.node)o=require.nodeRequire("fs"),f.get=function(a,e){var c=o.readFileSync(a,"utf8");0===c.indexOf("\ufeff")&&(c=c.substring(1));e(c)};else if("xhr"===
g.env||!g.env&&f.createXhr())f.get=function(a,e,c,d){var b=f.createXhr(),h;b.open("GET",a,!0);if(d)for(h in d)d.hasOwnProperty(h)&&b.setRequestHeader(h.toLowerCase(),d[h]);if(g.onXhr)g.onXhr(b,a);b.onreadystatechange=function(){var d;4===b.readyState&&(d=b.status,399<d&&600>d?(d=Error(a+" HTTP status: "+d),d.xhr=b,c(d)):e(b.responseText))};b.send(null)};else if("rhino"===g.env||!g.env&&"undefined"!==typeof Packages&&"undefined"!==typeof java)f.get=function(a,e){var c,d,b=new java.io.File(a),h=java.lang.System.getProperty("line.separator"),
b=new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(b),"utf-8")),f="";try{c=new java.lang.StringBuffer;(d=b.readLine())&&(d.length()&&65279===d.charAt(0))&&(d=d.substring(1));for(c.append(d);null!==(d=b.readLine());)c.append(h),c.append(d);f=String(c.toString())}finally{b.close()}e(f)};else if("xpconnect"===g.env||!g.env&&"undefined"!==typeof Components&&Components.classes&&Components.interfaces)l=Components.classes,i=Components.interfaces,Components.utils["import"]("resource://gre/modules/FileUtils.jsm"),
f.get=function(a,e){var c,d,b={},f=new FileUtils.File(a);try{c=l["@mozilla.org/network/file-input-stream;1"].createInstance(i.nsIFileInputStream),c.init(f,1,0,!1),d=l["@mozilla.org/intl/converter-input-stream;1"].createInstance(i.nsIConverterInputStream),d.init(c,"utf-8",c.available(),i.nsIConverterInputStream.DEFAULT_REPLACEMENT_CHARACTER),d.readString(c.available(),b),d.close(),c.close(),e(b.value)}catch(g){throw Error((f&&f.path||"")+": "+g);}};return f});